Repository openshift-knative/serverless-operator, pull requests merged in 2019-10, with the labels that each got.

#9 [SRVKS-272] Change email address to actually supported address.
  olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#8 Facilitate local testing
  olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml
  test/clients.go
  test/e2e-tests.sh
  test/e2e/deployment_test.go
Labels: approved, lgtm, size/M

#10 Bump to k-s-o v0.8.1-1.1.0-03
  olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, size/XS

#12 Add httpd-tools for htpasswd
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#11 Create test users with view and edit roles
  openshift/identity/htpasswd.yaml
  test/clients.go
  test/e2e-tests.sh
  test/e2e/deployment_test.go
  test/e2e/knative_serving_test.go
  test/service.go
Labels: approved, lgtm, size/L

#13 Bump to v0.8.1-1.1.0-04
  olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, size/XS

#15 Update k-o-i version to 0.0.9 and k-s-o to 1.1.0-05.
  olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#14 Tests for project admin
  test/clients.go
  test/e2e-tests.sh
  test/e2e/knative_serving_test.go
Labels: approved, lgtm, size/M

#17 Add CSV for 1.2.0, including knative-serving 0.9.0
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  olm-catalog/serverless-operator/serverless-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, size/L

#20 Use a nested structure for OLM metadata
  olm-catalog/serverless-operator/1.0.0/serverless-operator.v1.0.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.0.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.1.0/serverless-operator.v1.1.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.1.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.2.0/serverless-operator.v1.2.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.2.0/serving_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm, size/L

#22 Add Service Mesh as an OLM dependency in Serverless Operator CSV
  olm-catalog/serverless-operator/serverless-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#19 Rewrite of E2E scripts to open them to hecking need with various enhancements and bugfixes
  .editorconfig
  .gitignore
  hack/dependencies.sh
  hack/install.sh
  hack/lib/__sources__.bash
  hack/lib/catalogsource.bash
  hack/lib/common.bash
  hack/lib/namespaces.bash
  hack/lib/scaleup.bash
  hack/lib/serverless.bash
  hack/lib/servicemesh.bash
  hack/lib/ui.bash
  hack/lib/vars.bash
  hack/teardown.sh
  openshift/identity/htpasswd.yaml
  test/e2e-tests.sh
  test/flags.go
  test/lib.bash
Labels: approved, lgtm, size/XXL

#21 Depend on ServiceMesh operator
  README.md
  olm-catalog/serverless-operator/1.2.0/serverless-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#24 [SRVKS-255] Add the keyword 'Knative' into the short description.
  olm-catalog/serverless-operator/1.2.0/serverless-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
