Repository openshift-knative/serverless-operator, pull requests merged in 2019-12, with the labels that each got.

#43 Make the repository testable against arbitrary clusters.
  Makefile
  README.md
  hack/lib/catalogsource.bash
  hack/lib/vars.bash
  hack/publish.sh
  olm-catalog/serverless-operator/1.3.0/serverless-operator.v1.3.0.clusterserviceversion.yaml
  test/lib.bash
Labels: approved, lgtm, size/M

#45 Run all knative-serving tests in parallel as upstream does.
  test/lib.bash
Labels: approved, lgtm, size/S

#49 Fix teardown condition to skip in CI builds properly.
  test/lib.bash
Labels: approved, lgtm, size/XS

#42 Replace OwnerRefs on Routes with Finalizer.
  CHANGELOG.md
  serving/ingress/pkg/controller/common/reconciler.go
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  serving/ingress/pkg/controller/resources/route.go
  serving/ingress/pkg/controller/resources/route_test.go
Labels: approved, lgtm, size/M

#48 Improve the developer experience.
  Makefile
  README.md
  hack/catalog.sh
  hack/dev.sh
  hack/images.sh
  hack/lib/catalogsource.bash
  hack/publish.sh
Labels: approved, size/L

#51 Fix OLM namespace
  hack/lib/catalogsource.bash
  hack/lib/serverless.bash
  hack/lib/vars.bash
  test/subscription.go
Labels: approved, lgtm, size/M

#53 Invocation of upstream knative/serving-operator e2e tests
  hack/lib/serverless.bash
  test/e2e-tests.sh
  test/lib.bash
  test/patches/SRVKS-241-knative-serving-operator-skip-configure.patch
Labels: approved, lgtm, ok-to-test, size/L

#57 Fix 4.1 upgrade
  CHANGELOG.md
  hack/lib/common.bash
  olm-catalog/serverless-operator/1.3.0/serverless-operator.v1.3.0.clusterserviceversion.yaml
  test/lib.bash
Labels: approved, lgtm, size/M

#52 Completely separate E2E and rolling upgrades
  test/e2e-tests.sh
  test/lib.bash
  test/upgrade-tests.sh
Labels: approved, size/L
