Repository openshift-knative/serverless-operator, pull requests merged in 2020-08, with the labels that each got.

#276 Restore the original maxReplicas for activator HPA
  test/serving.bash
Labels: approved, lgtm

#395 [SRVCOM-917] Update CSV description links - master
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm

#397 Describe CRC based testing better.
  README.md
  test/lib.bash
Labels: approved, lgtm

#396 [SRVCOM-917] Update CSV description links - release-1.8
  olm-catalog/serverless-operator/1.8.0-rc1/serverless-operator.v1.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#409 [RELEASE-1.8] Move to the new bundle format.
  .gitignore
  hack/catalog.sh
  hack/dev.sh
  hack/install.sh
  hack/lib/catalogsource.bash
  hack/lib/serverless.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.0.0/serverless-operator.v1.0.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.0.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.1.0/serverless-operator.v1.1.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.1.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.2.0/serverless-operator.v1.2.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.2.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.3.0/serverless-operator.v1.3.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.3.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.0/serverless-operator.v1.4.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.4.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.4.1/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.5.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.5.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.6.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.1/serverless-operator.v1.7.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.8.0-rc1/serverless-operator.v1.8.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/container.yaml
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/metadata/annotations.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/serving.bash
Labels: approved, do-not-merge/hold

#405 Without service mesh, no scaling is the reasonable default
  Makefile
  README.md
  hack/lib/vars.bash
Labels: approved, lgtm

#406 [BACKPORT][SRVKS-588] Avoid resourceVersion churn due to constant status resetting. (#377)
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#411 Scale up worker nodes to 6 when running upstream e2e tests
  Makefile
  test/upstream-e2e-tests.sh
Labels: approved, lgtm

#412 Reduce hacks needed for bundle format CI.
  hack/lib/catalogsource.bash
  olm-catalog/serverless-operator/index.Dockerfile
Labels: approved

#368 [SRVKS-578] Add service mesh installation and sidecar injection scripts
  Makefile
  README.md
  hack/lib/__sources__.bash
  hack/lib/mesh.bash
  hack/mesh.sh
  knative-operator/deploy/resources/kourier/README.md
Labels: approved, lgtm

#410 Change default channel to 4.3
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/metadata/annotations.yaml
Labels: approved, lgtm
