Repository openshift-knative/serverless-operator, pull requests merged in 2020-03, with the labels that each got.

#116 [SRVKS-405,406,407] Remove ServiceMesh dependencies
  hack/dependencies.sh
  hack/dev.sh
  hack/install.sh
  knative-operator/deploy/resources/kourier/debug-log.patch
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-openshift.yaml
  knative-operator/deploy/resources/kourier/kourier-v0.3.10.yaml
  knative-operator/deploy/resources/servicemesh/networkpolicies.yaml
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
  knative-operator/pkg/controller/knativeserving/servicemesh/servicemesh.go
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
  serving/ingress/pkg/controller/common/reconciler.go
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  test/e2e-tests.sh
  test/e2e/knative_serving_test.go
  test/upgrade-tests.sh
Labels: approved, lgtm, size/XL

#146 Use official 0.12.1 operator image
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#119 Add IMAGE_3scale-* env values to replace Kourier images
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#148 Update kn ConsoleCLIDownload links to point to 0.12 builds
  knative-operator/deploy/resources/console_cli_download_kn.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#150 Use kourier image produced by fork and add related images.
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, size/XS

#151 Add Dockerfile for productization
  serving/ingress/Dockerfile.productization
Labels: approved, size/M

#152 Add IsNoMatchError to skip kind ServiceMeshControlPlane not found error
  knative-operator/pkg/controller/knativeserving/servicemesh/servicemesh.go
Labels: approved, lgtm, size/XS

#153 Don't check the upgrade probe for readiness.
  test/lib.bash
Labels: approved, size/XS

#141 Remove shortname ks from knativeservings.serving.knative.dev CRD
  olm-catalog/serverless-operator/1.5.0/serving_v1alpha1_knativeserving_crd.yaml
Labels: size/XS

#156 Removing myself from approver/reviewer
  OWNERS_ALIASES
Labels: size/XS

#155 Use a differently named service to workaround kourier bug.
  test/e2e/knative_serving_test.go
Labels: approved, lgtm, size/XS

#143 Dump CSVs on failure
  hack/lib/serverless.bash
Labels: approved, lgtm, size/XS

#162 Update kourier to the latest version.
  knative-operator/deploy/resources/kourier/debug-log.patch
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.12-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.12.yaml
  knative-operator/deploy/resources/kourier/proxyv2-image.patch
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#164 Fix log format
  serving/ingress/pkg/controller/common/reconciler.go
Labels: approved, lgtm, size/XS

#165 Kick CI to promote a new set of images.
  ci
Labels: approved, size/XS

#166 Update spec.description in 1.5.0 CSV
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, size/S

#168 Make sure to use the proper group for getting knativeserving version
  test/lib.bash
Labels: approved, lgtm, size/XS

#169 Update description from the 1.5 branch and apply to 1.6.
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
Labels: size/S

#176 Remove obsoleted egress setting
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/common/openshift_test.go
Labels: lgtm, size/S

#173 Update Knative Serving + operator to 0.13.
  hack/install.sh
  hack/lib/serverless.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
  test/lib.bash
  test/upgrade-tests.sh
Labels: approved, lgtm, size/M

#174 Bring back full-blown KnativeServing config for backwards compat tests
  hack/lib/serverless.bash
  test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeserving_cr.yaml
Labels: approved, lgtm, size/S

#171 Move client role setup into t.Run()
  test/e2e/knative_serving_test.go
Labels: approved, lgtm, size/S

#181 [SRKVS-462] Skip proxy e2e test.
  test/e2e/knative_serving_test.go
Labels: approved

#180 [SRVKS-460] Watch routes to reconcile them on changes.
  serving/ingress/pkg/controller/ingress/ingress_controller.go
Labels: approved, lgtm

#186 Add more context to all errors and improve logging throughout.
  knative-operator/pkg/common/deployment.go
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm

#187 [SRVKS-468] Support nightly versions of OCP4.3 too.
  knative-operator/pkg/webhook/knativeserving/webhook_validating_test.go
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#172 extend support for HTTPS_PROXY to support egress proxies in Knative
  knative-operator/pkg/common/deployment.go
  knative-operator/pkg/common/deployment_test.go
Labels: lgtm, size/M

#170 Hide Serving CRDs in developer catalog
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#177 Add logging to our cleanup routine to know what gets deleted when.
  test/lib.bash
  test/service.go
  test/subscription.go
  test/v1alpha1/knativeserving.go
Labels: approved, size/S

#179 Print error log when Cleanup func failed
  test/clients.go
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#189 Enable 'kubectl explain' to work [SRVKS-437]
  olm-catalog/serverless-operator/1.6.0/operator_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm

#175 Always apply Kourier manifest in the reconcile loop
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm, size/XS

#190 Add techpreview-4.3 and techpreview-4.4 channels
  hack/lib/serverless.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/lib.bash
Labels: approved, lgtm

#192 update images to 1.5.0 instead of nightly
  hack/catalog.sh
Labels: approved, lgtm

#191 [SRVKS-478] Update manifestival to fix transformer bug.
  knative-operator/Gopkg.lock
  knative-operator/Gopkg.toml
  knative-operator/pkg/controller/knativeserving/kourier/kourier_test.go
  knative-operator/pkg/controller/knativeserving/kourier/testdata/kourier-latest.yaml
  knative-operator/vendor/github.com/manifestival/manifestival/dry.go
  knative-operator/vendor/github.com/manifestival/manifestival/filter.go
  knative-operator/vendor/github.com/manifestival/manifestival/manifestival.go
  knative-operator/vendor/github.com/manifestival/manifestival/patch/patch.go
  knative-operator/vendor/github.com/manifestival/manifestival/transform.go
Labels: approved, lgtm

#193 Update status of KnativeServing at the end of each reconcile cycle.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm

#194 Prevent more than one KnativeServing CR in any namespace [SRVKS-415]
  knative-operator/deploy/operator.yaml
  knative-operator/pkg/webhook/knativeserving/webhook_validating.go
  knative-operator/pkg/webhook/knativeserving/webhook_validating_test.go
Labels: approved, lgtm

#196 Run tests on debug log level.
  test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeserving_cr.yaml
Labels: approved, lgtm

#195 [SRVKS-482] Upgrade Knative Serving to 0.13.1.
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
  test/lib.bash
Labels: approved, lgtm

#199 Always handle a finalizer if in the list.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#198 [SRVKS-479] Delete orphaned VirtualService
  knative-operator/pkg/apis/addtoscheme_serving_v1alpha1.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#185 Watch events for Kourier resources change
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/testdata/console_cli_download_kn.yaml
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm

#200 Enable knative-serving-operator's debug log for CI
  hack/lib/serverless.bash
Labels: lgtm

#197 [SRVKS-438] Adjust channel names to the proposal and make the new one the default.
  hack/lib/vars.bash
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved

#206 Build all of our components with Golang 1.13.
  knative-operator/Dockerfile
  serving/ingress/Dockerfile
Labels: approved, lgtm

#204 Uniformly update all image references to 0.13.1.
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
Labels: approved

#202 Add default behavior for HA
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/common/openshift_test.go
  olm-catalog/serverless-operator/1.6.0/operator_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm

#201 Add unit test for delete orphaned virtualservice
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved, lgtm

#208 kn ConsoleCLIDownload version 0.13.1
  knative-operator/deploy/resources/console_cli_download_kn.yaml
Labels: approved, lgtm, ok-to-test

#211 Default images to the prebuilt 1.6.0 images.
  hack/catalog.sh
Labels: approved

#210 Use the correct channel in operator e2e tests.
  test/flags.go
  test/lib.bash
Labels: approved, lgtm

#203 [SRVKS-484] Make knative-operator and ingress log with readable timestamps.
  knative-operator/cmd/manager/main.go
  serving/ingress/cmd/manager/main.go
  serving/ingress/pkg/controller/ingress/ingress_controller.go
Labels: approved

#215 Bootstrap the 1.7.0 release.
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/lib.bash
Labels: approved, lgtm

#217 Remove trailing whitespace
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#212 Rename REQUIRED_NAMESPACE to REQUIRED_SERVING_NAMESPACE
  knative-operator/deploy/operator.yaml
  knative-operator/pkg/webhook/knativeserving/webhook_validating.go
  knative-operator/pkg/webhook/knativeserving/webhook_validating_test.go
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#213 Refactor min openshift version validation
  knative-operator/deploy/operator.yaml
  knative-operator/pkg/webhook/knativeserving/webhook_validating.go
  knative-operator/pkg/webhook/knativeserving/webhook_validating_test.go
  knative-operator/pkg/webhook/util/util.go
Labels: approved, do-not-merge/hold, lgtm

#214 Refactor patch response from raw
  knative-operator/pkg/webhook/knativeserving/webhook_mutating.go
  knative-operator/pkg/webhook/util/util.go
Labels: approved, lgtm

#219 Refactor image override logic
  hack/lib/serverless.bash
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/common/openshift_test.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/common/util_test.go
  test/lib.bash
Labels: approved, lgtm

#220 Some file rename
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/serving_test.go
Labels: approved, lgtm
