Repository openshift-knative/serverless-operator, pull requests merged in 2020-06, with the labels that each got.

#326 Dockerfile for serverless-operator-src image
  openshift/ci-operator/source-image/Dockerfile
Labels: approved

#334 Drop cluster dump
  test/lib.bash
Labels: approved

#333 Use Serverless must gather
  test/lib.bash
Labels: approved, lgtm

#329 Add eventing to the source image
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#304 Use knative-serving-src image for running tests
  hack/catalog.sh
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/lib.bash
  test/serving.bash
  test/upgrade-tests.sh
Labels: approved, lgtm

#335 Do not clone Knative Eventing and remove third-party operator test suites
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/eventing.bash
  test/lib.bash
  test/serving.bash
Labels: approved, do-not-merge/hold, lgtm

#331 Update Knative Serving to 0.14.1.
  hack/lib/vars.bash
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#336 Update Serving src image to 0.14.1 and define the version in Dockerfile
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, do-not-merge/hold

#342 Update envoy image to enable graceful shutdown.
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#343 Adding tracing namespace...
  hack/lib/tracing.bash
  hack/lib/vars.bash
Labels: approved, lgtm

#340 Update kourier manifest to 0.14.
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.14-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.14.yaml
Labels: approved

#323 Allow upgrades to OCP that is not yet available via channel (#303)
  hack/lib/vars.bash
  test/serving.bash
Labels: approved, lgtm

#347 [SRVKS-511] Use spec.resources to bump webhook memory limit to 1G
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/serving_test.go
Labels: approved, lgtm

#348 Patch config to use explicit broker class
  test/eventing.bash
Labels: lgtm

#349 A few tests validating SRVKS-511 logic
  knative-operator/pkg/common/serving_test.go
Labels: approved

#338 Update kn-cli-artifacts image to v0.14.0
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
Labels: ok-to-test

#355 Prepare for 1.8.0-rc1 release
  hack/catalog.sh
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.8.0-rc1/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.8.0-rc1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.8.0-rc1/serverless-operator.v1.8.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, lgtm

#358 [SRVLS-264] Install knative components in openshift-serverless
  hack/lib/namespaces.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
  test/deployment.go
  test/e2e/knative_eventing_test.go
  test/e2e/knative_serving_test.go
  test/serving.bash
  test/subscription.go
Labels: approved, lgtm
