Repository openshift-knative/serverless-operator, pull requests merged in 2020-07, with the labels that each got.

#360 Confirm upgrade of knativeserving version from hard-coded value
  test/serving.bash
Labels: lgtm

#366 [SRVKS-588] Fix churn on KnativeServing CR caused by constant spec overriding.
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm

#369 Log the CSV the operator is installed with.
  hack/lib/serverless.bash
Labels: approved

#367 [SRVKS-588] Fix churn on KnativeServing CR caused by constant spec overriding.
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator/1.8.0-rc1/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.8.0-rc1/operator_v1alpha1_knativeserving_crd.yaml
Labels: approved

#365 Confirm upgrade of knativeserving version from hard-coded value
  test/serving.bash
Labels: approved, lgtm

#317 [BACKPORT][SRVKS-567] Set KnativeServing CR status to "Dependency installing" whenever Kourier installation failed
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm

#372 Adding CSV bumps for 1.7.2 release
  knative-operator/Gopkg.lock
  knative-operator/Gopkg.toml
  knative-operator/vendor/github.com/openshift/console-operator/LICENSE
  knative-operator/vendor/github.com/openshift/console-operator/cmd/console/main.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/api/api.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/cmd/operator/cmd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/cmd/version/cmd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/clientwrapper/without_secret.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/clidownloads/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/resourcesyncdestination/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/route/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/service/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/errors/custom_logo_errors.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/errors/sync_errors.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/metrics/metrics.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operator/operator.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operator/sync_v400.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operatorclient/operatorclient.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/starter/starter.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/status/status.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_custom_logo.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_ocp.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_okd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/configmap.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/service_ca.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/trusted_ca.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/config_builder.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/config_merger.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/types.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/deployment/deployment.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/oauthclient/oauthclient.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/route/route.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/secret/secret.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/service/service.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/util/util.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/version/version.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/crypto/random.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/clientset.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/config.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/console-operator.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/framework.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/logs.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/utils.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/util.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/util_http.go
  knative-operator/vendor/github.com/openshift/console-operator/tools/import-verifier/import-verifier.go
  knative-operator/vendor/knative.dev/serving-operator/pkg/reconciler/knativeserving/common/ha.go
  knative-operator/vendor/knative.dev/serving-operator/version/version.go
  olm-catalog/serverless-operator/1.7.2/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.2/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.2/serverless-operator.v1.7.2.clusterserviceversion.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/eventing.bash
Labels: approved, lgtm

#377 [SRVKS-588] Avoid resourceVersion churn due to constant status resetting.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#376 Script and make target for running all tests
  Makefile
  test/e2e-tests.sh
Labels: approved, lgtm

#378 Remove tech-preview and preview-4.3 channels
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, lgtm

#379 Decrease SLO to 95% if the previous serving version is earlier than 0.14
  test/serving.bash
Labels: approved, lgtm

#384 Drop Kourier debug config
  hack/lib/catalogsource.bash
  knative-operator/deploy/resources/kourier/debug-log.patch
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.14-debug.yaml
Labels: approved, lgtm

#385 Remove diff to avoid panic due to comparing unexported fields.
  knative-operator/Gopkg.lock
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#346 Reuse test execution for Eventing from knative-eventing-src
  hack/lib/vars.bash
  test/eventing.bash
Labels: approved, lgtm

#391 Restoring accidentally-deleted e2e tests
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.15.yaml
  olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
  test/e2e/knative_eventing_test.go
  test/e2e/knative_serving_test.go
  test/servinge2e/verify_networkpolicy_test.go
Labels: approved, lgtm

#382 SRVCOM-921 Separate serverless tests from third-party test suites
  Makefile
  README.md
  hack/lib/catalogsource.bash
  hack/lib/ui.bash
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/eventing.bash
  test/lib.bash
  test/upgrade-tests.sh
  test/upstream-e2e-tests.sh
Labels: approved, lgtm
