Repository openshift-knative/serverless-operator, pull requests merged in 2020-04, with the labels that each got.

#227 Update manifestival to fix SRVKS-483
  knative-operator/Gopkg.lock
  knative-operator/Gopkg.toml
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
  knative-operator/vendor/github.com/manifestival/manifestival/client.go
  knative-operator/vendor/github.com/manifestival/manifestival/filter.go
  knative-operator/vendor/github.com/manifestival/manifestival/manifestival.go
  knative-operator/vendor/github.com/manifestival/manifestival/overlay/overlay.go
Labels: approved, lgtm

#229 Add a test that verifies the internal registry works.
  test/lib.bash
Labels: approved, lgtm

#223 Eventing enabled
  hack/lib/serverless.bash
  hack/lib/vars.bash
  knative-operator/pkg/controller/add_knativeeventing.go
  knative-operator/pkg/webhook/add_knativeeventing.go
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
  test/Gopkg.lock
  test/clients.go
  test/deployment.go
  test/e2e/knative_eventing_test.go
  test/service.go
  test/v1alpha1/knativeeventing.go
  test/vendor/knative.dev/eventing-operator/LICENSE
  test/vendor/knative.dev/eventing-operator/cmd/manager/kodata/HEAD
  test/vendor/knative.dev/eventing-operator/cmd/manager/kodata/LICENSE
  test/vendor/knative.dev/eventing-operator/cmd/manager/kodata/VENDOR-LICENSE
  test/vendor/knative.dev/eventing-operator/cmd/manager/kodata/refs
  test/vendor/knative.dev/eventing-operator/pkg/apis/eventing/v1alpha1/doc.go
  test/vendor/knative.dev/eventing-operator/pkg/apis/eventing/v1alpha1/knativeeventing_lifecycle.go
  test/vendor/knative.dev/eventing-operator/pkg/apis/eventing/v1alpha1/knativeeventing_types.go
  test/vendor/knative.dev/eventing-operator/pkg/apis/eventing/v1alpha1/register.go
  test/vendor/knative.dev/eventing-operator/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/clientset.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/doc.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/scheme/doc.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/scheme/register.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  test/vendor/knative.dev/eventing-operator/pkg/client/clientset/versioned/typed/eventing/v1alpha1/knativeeventing.go
  test/vendor/knative.dev/eventing-operator/test/config
  test/vendor/knative.dev/pkg/apis/duck/cached.go
  test/vendor/knative.dev/pkg/apis/duck/doc.go
  test/vendor/knative.dev/pkg/apis/duck/enqueue.go
  test/vendor/knative.dev/pkg/apis/duck/interface.go
  test/vendor/knative.dev/pkg/apis/duck/patch.go
  test/vendor/knative.dev/pkg/apis/duck/proxy.go
  test/vendor/knative.dev/pkg/apis/duck/register.go
  test/vendor/knative.dev/pkg/apis/duck/typed.go
  test/vendor/knative.dev/pkg/apis/duck/unstructured.go
  test/vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1/doc.go
  test/vendor/knative.dev/pkg/apis/duck/v1/register.go
  test/vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/doc.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  test/vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  test/vendor/knative.dev/pkg/apis/duck/verify.go
  test/vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  test/vendor/knative.dev/pkg/apis/v1alpha1/doc.go
  test/vendor/knative.dev/pkg/apis/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm

#231 [SRVKS-505] Verify the default is HA
  test/Gopkg.lock
  test/Gopkg.toml
  test/e2e/knative_serving_test.go
  test/service.go
  test/vendor/knative.dev/serving-operator/pkg/apis/serving/v1alpha1/knativeserving_types.go
  test/vendor/knative.dev/serving-operator/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/clientset.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/doc.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/scheme/doc.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/scheme/register.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/typed/serving/v1alpha1/knativeserving.go
  test/vendor/knative.dev/serving-operator/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
Labels: approved, lgtm

#226 Force cluster upgrade
  test/lib.bash
Labels: approved

#225 Force cluster upgrade
  test/lib.bash
Labels: approved

#233 Nail upstream release versions to 0.13.2
  knative-operator/Gopkg.lock
  knative-operator/Gopkg.toml
  knative-operator/vendor/knative.dev/eventing-operator/pkg/reconciler/knativeeventing/knativeeventing.go
  knative-operator/vendor/knative.dev/eventing-operator/test/resources/verify.go
  knative-operator/vendor/knative.dev/eventing-operator/version/version.go
  knative-operator/vendor/knative.dev/serving-operator/version/version.go
Labels: approved, lgtm

#234 Rename knative-serving-openshift -> knative-openshift
  knative-operator/Dockerfile
  knative-operator/README.md
  knative-operator/build/Dockerfile
  knative-operator/build/bin/entrypoint
  knative-operator/cmd/manager/main.go
  knative-operator/deploy/operator.yaml
  knative-operator/deploy/role.yaml
  knative-operator/deploy/role_binding.yaml
  knative-operator/deploy/service_account.yaml
  knative-operator/pkg/webhook/webhook.go
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
  test/service.go
Labels: approved, lgtm

#232 [SRVKS-485] Introduce GA channels and make 4.3 the default.
  hack/lib/serverless.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/flags.go
  test/lib.bash
Labels: approved

#222 Provide options to specify CHANNEL and SOURCE for upgrades
  hack/lib/serverless.bash
  hack/lib/vars.bash
  test/lib.bash
Labels: approved, lgtm

#224 [SRVKS-444] Use different injection mechanism to get proxy certs as well.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#236 Update Knative Serving references to 0.13.2.
  hack/lib/vars.bash
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
  test/lib.bash
Labels: approved, lgtm

#239 Upgrade kourier to latest and new fork.
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.13-debug.yaml
  knative-operator/deploy/resources/kourier/kourier-release-0.13.yaml
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#242 Generalize environment variable setting to deployments.
  knative-operator/pkg/common/deployment.go
  knative-operator/pkg/common/deployment_test.go
  knative-operator/pkg/common/serving_test.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#244 Run HA tests against the correct namespace and fix short-circuit.
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#245 Sort environment variables to make unit test stable.
  knative-operator/pkg/common/deployment_test.go
Labels: approved

#247 SRVKS-509, remove operators.operatorframework.io/internal-objects ann…
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#241 [SRVKS-513] Manually combine configmaps for service-ca and trusted-ca.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved

#243 Replace Kourier deployments replica count based on the HighAvailability setting
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
  test/e2e/knative_serving_test.go
Labels: approved, lgtm, ok-to-test

#250 Add activator HA check.
  test/e2e/knative_serving_test.go
Labels: approved

#235 fix(docs): Update docs links
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#238 Make it possible to choose different repos in tests
  hack/lib/vars.bash
  test/lib.bash
Labels: approved, lgtm

#251 [SRVKS-518] Implement a kick mechanism to force cert rotation in the controller.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved, lgtm

#246 Remove the spec.config block from KnativeServing example
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#256 Remove trailing whitespace in description
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved

#258 Fix approve_csv to actually use the oc replace command
  hack/lib/serverless.bash
Labels: approved, lgtm

#253 [SRVKS-289] Set default domainTemplate to {{.Name}}-{{.Namespace}}.{{Domain}}
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/serving_test.go
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#255 Test route conflict behavior.
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
  test/e2e/knative_serving_test.go
Labels: approved

#240 Execution of eventing tests
  .editorconfig
  hack/lib/ui.bash
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/eventing.bash
  test/lib.bash
  test/serving.bash
  test/upgrade-tests.sh
Labels: approved, lgtm

#260 Collecting build artifacts
  hack/lib/ui.bash
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/upgrade-tests.sh
Labels: approved, lgtm

#263 Quote channel to prevent an error from parsing a number
  hack/lib/serverless.bash
Labels: approved

#257 CSV updates for GA
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved

#269 Revert "Quote channel to prevent an error from parsing a number (#263)"
  hack/lib/serverless.bash
Labels: approved

#272 Fix an error with undefined ARTIFACTS_DIR
  hack/lib/vars.bash
Labels: approved, lgtm

#267 Eventing Operator tests execution
  hack/lib/serverless.bash
  test/e2e-tests.sh
  test/eventing.bash
  test/lib.bash
  test/serving.bash
Labels: approved, lgtm

#262 [SRVKS-470 SRVKS-472 SRVKS-473] Enable HA test suite execution
  test/serving.bash
Labels: approved

#275 Hardcode 1.7.0 image references in the CSV.
  hack/catalog.sh
Labels: approved

#280 Change value keys to image under spec.relatedImages
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#281 Change value keys to image under spec.relatedImages
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#279 Properly end prober 1.7
  test/lib.bash
  test/serving.bash
Labels: approved
