Repository openshift-knative/serverless-operator, pull requests merged in 2020-05, with the labels that each got.

#277 Serverless operator e2e test cleanup and reorganize
  test/e2e-tests.sh
  test/e2e/knative_serving_test.go
  test/eventing.bash
  test/lib.bash
  test/service.go
  test/serving.bash
  test/servinge2e/deploy_kn_k8s_svc_in_same_namespace_test.go
  test/servinge2e/user_permissions_test.go
  test/servinge2e/verify_deploy_resources_test.go
  test/servinge2e/verify_http_and_https_test.go
  test/servinge2e/verify_route_conflict_test.go
Labels: approved, lgtm, ok-to-test

#287 Image override with deployment name
  knative-operator/pkg/common/eventing.go
  knative-operator/pkg/common/eventing_test.go
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/common/util_test.go
Labels: approved, lgtm

#294 [SRVKS-535] Reduce churn on route objects by pre-defaulting it.
  serving/ingress/pkg/controller/ingress/ingress_controller.go
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  serving/ingress/pkg/controller/ingress/resources/route.go
  serving/ingress/pkg/controller/ingress/resources/route_test.go
Labels: approved, lgtm

#295 Fix image overrides for env vars that contain underscores
  knative-operator/pkg/common/eventing_test.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/common/util_test.go
  test/e2e/disallowed_img_registry.go
  test/e2e/knative_eventing_test.go
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#299 [SRVKS-535] Reduce churn on route objects by pre-defaulting it.
  serving/ingress/pkg/controller/ingress/ingress_controller.go
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  serving/ingress/pkg/controller/ingress/resources/route.go
  serving/ingress/pkg/controller/ingress/resources/route_test.go
Labels: approved, lgtm

#291 Remove unnecessary openshift/console-operator dep
  knative-operator/Gopkg.lock
  knative-operator/vendor/github.com/openshift/console-operator/LICENSE
  knative-operator/vendor/github.com/openshift/console-operator/cmd/console/main.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/api/api.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/cmd/operator/cmd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/cmd/version/cmd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/clientwrapper/without_secret.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/clidownloads/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/resourcesyncdestination/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/route/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/controllers/service/controller.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/errors/custom_logo_errors.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/errors/sync_errors.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/metrics/metrics.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operator/operator.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operator/sync_v400.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/operatorclient/operatorclient.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/starter/starter.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/status/status.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_custom_logo.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_ocp.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/brand_okd.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/configmap.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/service_ca.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/configmap/trusted_ca.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/config_builder.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/config_merger.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/consoleserver/types.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/deployment/deployment.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/oauthclient/oauthclient.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/route/route.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/secret/secret.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/service/service.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/subresource/util/util.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/console/version/version.go
  knative-operator/vendor/github.com/openshift/console-operator/pkg/crypto/random.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/clientset.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/config.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/console-operator.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/framework.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/logs.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/framework/utils.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/util.go
  knative-operator/vendor/github.com/openshift/console-operator/test/e2e/util_http.go
  knative-operator/vendor/github.com/openshift/console-operator/tools/import-verifier/import-verifier.go
Labels: approved, lgtm

#278 Report error when prober test fails
  test/lib.bash
  test/serving.bash
Labels: approved, lgtm

#300 [WIP] bump to 1.8.0, but keep images at 0.13
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/serving.bash
Labels: do-not-merge/work-in-progress

#301 Bumping for 1.7.1
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.1/serverless-operator.v1.7.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/serving.bash
Labels: approved, lgtm

#307 Hardcode 1.7.0 image references for proper upgrade testing.
  olm-catalog/serverless-operator/1.7.0/serverless-operator.v1.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#309 Move the default catalog references to 1.7.1.
  hack/catalog.sh
Labels: approved, lgtm

#306 Update Knative Serving to 0.13.3 and reenable upgrade tests.
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.7.1/serverless-operator.v1.7.1.clusterserviceversion.yaml
  test/serving.bash
Labels: approved, lgtm

#312 Eventing: Like serving, try to use an image template
  test/eventing.bash
Labels: approved, lgtm

#311 Update 1.8.0 to Serving 0.13.3 and reenable prober tests.
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
  test/serving.bash
Labels: approved, lgtm

#303 Allow upgrades to OCP that is not yet available via channel
  hack/lib/vars.bash
  test/serving.bash
Labels: approved, lgtm

#315 Create new 4.5 channel with 1.7.1
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, lgtm

#316 [SRVKS-567] Set KnativeServing CR status to "Dependency installing" whenever Kourier installation failed
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
Labels: approved, lgtm

#293 [SRVCOM-790] Add grafana template for OpenShift dashboard
  knative-operator/deploy/resources/dashboards/grafana-dash-knative.yaml
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/dashboard/dashboard.go
  knative-operator/pkg/controller/knativeserving/dashboard/testdata/grafana-dash-knative.yaml
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved, lgtm

#320 Bump operator version in preview-4.3 channel
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, lgtm

#321 Revert "Bump operator version in preview-4.3 channel"
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, lgtm

#319 Update CSV to have same 0.13.x bits like the 1.7.1 has
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
Labels: approved, lgtm
