Repository openshift-knative/serverless-operator, pull requests merged in 2020-01, with the labels that each got.

#64 Add next version and use nightly images by default.
  CHANGELOG.md
  hack/catalog.sh
Labels: approved, lgtm, size/XS

#73 Add relatedImages block
  olm-catalog/serverless-operator/1.4.0/serverless-operator.v1.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#68 Create ConsoleCLIDownload CR for kn CLI
  knative-operator/deploy/resources/console_cli_download_kn.yaml
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm, ok-to-test, size/M

#75 Add network policy for cluster-local-gateway
  knative-operator/deploy/resources/servicemesh/networkpolicies.yaml
  knative-operator/deploy/resources/servicemesh/servicemesh.yaml
  knative-operator/pkg/controller/knativeserving/servicemesh/servicemesh.go
Labels: approved, lgtm, size/M

#83 Make subscription source and channel configurable in e2e test
  test/flags.go
  test/lib.bash
  test/subscription.go
Labels: approved, lgtm, size/S

#84 [SRVKS-397] Remove broken APIService and add a test so we don't regress.
  olm-catalog/serverless-operator/1.4.0/serverless-operator.v1.4.0.clusterserviceversion.yaml
  test/Gopkg.lock
  test/Gopkg.toml
  test/clients.go
  test/e2e/knative_serving_test.go
  test/vendor/k8s.io/kube-aggregator/LICENSE
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/defaults.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/register.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.deepcopy.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.defaults.go
  test/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiregistration_client.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiservice.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/generated_expansion.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  test/vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
  test/vendor/k8s.io/utils/pointer/pointer.go
  test/vendor/knative.dev/serving-operator/test/config
Labels: approved, lgtm, size/XXL

#82 Simplify logging utitilities and enable -x in CI.
  hack/lib/common.bash
  hack/lib/ui.bash
  test/e2e-tests.sh
  test/upgrade-tests.sh
Labels: approved, lgtm, size/L

#89 Upgrades: Choose the latest OCP version if there are more options
  test/lib.bash
Labels: approved, size/XS
