Repository openshift-knative/serverless-operator, pull requests merged in 2020-02, with the labels that each got.

#91 Support both the old and the new group of KnativeServings.
  hack/lib/serverless.bash
  knative-operator/Gopkg.lock
  knative-operator/deploy/resources/knative-serving-0.10.0.yaml
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/servicemesh/servicemesh.go
  knative-operator/pkg/controller/knativeservingobsolete/deploy
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller.go
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller_test.go
  olm-catalog/serverless-operator/1.4.0/serverless-operator.v1.4.0.clusterserviceversion.yaml
  test/e2e/knative_serving_test.go
  test/lib.bash
  test/v1alpha1/knativeserving.go
  test/v1alpha1/resources/serving.knative.dev_v1alpha1_knativeserving_cr_1.3.0.yaml
Labels: approved, lgtm, size/XXL

#92 SRVKS-411 remove IMAGE_default env
  olm-catalog/serverless-operator/1.4.0/serverless-operator.v1.4.0.clusterserviceversion.yaml
Labels: size/XS

#90 Upgrades: Choose the latest OCP version if there are more options
  test/lib.bash
Labels: approved, size/XS

#95 Delete the new CR when the old CR is removed and vice versa.
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller.go
Labels: approved, lgtm, size/S

#94 Fix the override logic from old to new to allow continuous mirroring.
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller.go
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller_test.go
Labels: approved, size/M

#96 Add 1.4.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.0/serving_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm, size/M

#97 Add 1.4.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.0/serving_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm, size/M

#100 Exclude gRPC tests on vSphere
  test/lib.bash
Labels: approved, lgtm, size/S

#99 Remove -l from the array of kubeconfigs
  test/lib.bash
Labels: approved, lgtm, size/XS

#104 Remove resources from 1.3.0 carrying a wrong ownerRef.
  knative-operator/deploy/resources/obsolete/knative-serving-0.10.0.yaml
  knative-operator/deploy/resources/obsolete/monitoring-1.3.0.yaml
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller.go
  test/upgrade-tests.sh
Labels: approved, lgtm, size/L

#105 Release 1.4.1
  knative-operator/deploy/resources/obsolete/knative-serving-0.10.0.yaml
  knative-operator/deploy/resources/obsolete/monitoring-1.3.0.yaml
  knative-operator/pkg/controller/knativeservingobsolete/knativeservingobsolete_controller.go
  olm-catalog/serverless-operator/1.4.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.4.1/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/upgrade-tests.sh
Labels: approved, lgtm, size/XL

#98 Remove -l from the array of kubeconfigs
  test/lib.bash
Labels: approved, lgtm, size/XS

#101 A better way to detect vSphere
  test/lib.bash
Labels: approved, lgtm, size/XS

#106 Pick the 1.4.1 stuff into master. (#105)
  olm-catalog/serverless-operator/1.4.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.4.1/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
Labels: approved, size/XL

#109 Wait for knative-serving-ingress ns to be deleted before new tests
  test/lib.bash
Labels: approved, lgtm, size/S

#111 Remove skips directive as it has been found to not be reliable.
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
  test/lib.bash
Labels: approved, lgtm, size/XS

#85 Install Kourier without removing Service Mesh
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-openshift.yaml
  knative-operator/deploy/resources/kourier/kourier-v0.3.8.yaml
  knative-operator/deploy/resources/kourier/proxyv2-image.patch
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/kourier/kourier.go
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  serving/ingress/pkg/controller/resources/route.go
  serving/ingress/pkg/controller/resources/route_test.go
  test/lib.bash
Labels: approved, lgtm, size/L

#112 Remove skips directive as it has been found to be unreliable.
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#115 Add knative-serving-operator to relatedImages in 1.4.1 CSV
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#117 Fix rolling upgrade wait condition
  test/lib.bash
Labels: approved, lgtm, size/XS

#120 Include workaround for LoadBalancer cleanup on Azure
  test/lib.bash
Labels: approved, lgtm, size/S

#123 Use the latest kourier gateway image
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-v0.3.8.yaml
Labels: approved, lgtm, size/S

#124 Add previous version install option to make install-previous
  Makefile
  README.md
  hack/install.sh
  hack/lib/serverless.bash
Labels: approved, lgtm, size/M

#127 Set default value to INSTALL_PREVIOUS_VERSION
  hack/lib/vars.bash
Labels: approved, lgtm, size/XS

#125 Remove CI-namespace references.
  hack/catalog.sh
  test/e2e-tests.sh
  test/upgrade-tests.sh
Labels: approved, lgtm, size/XS

#128 Fix condition for checking loadbalancers
  test/lib.bash
Labels: approved, lgtm, size/XS

#121 Add failfast option to run e2e to collect logs when failed
  test/e2e/knative_serving_test.go
  test/lib.bash
Labels: approved, lgtm, size/XS

#130 Update Kourier version to v0.3.9
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-v0.3.9.yaml
Labels: approved, lgtm, size/S

#118 Fix rolling upgrade wait condition - master
  test/lib.bash
Labels: approved, lgtm, size/XS

#137 Add failfast option to openshift specific e2e test
  test/lib.bash
Labels: approved, lgtm, size/XS

#136 [SRVKS-423] Remove CI-namespace references.
  hack/catalog.sh
Labels: approved, lgtm, size/XS

#132 Scale up worker nodes across all available zones
  hack/lib/scaleup.bash
Labels: approved, lgtm, size/M

#135 [SRVKS-423] Remove CI-namespace references.
  hack/catalog.sh
Labels: approved, lgtm, size/XS

#138 [SRVKS-427] Override all configuration we set as we have authority. Apply mutations on update.
  knative-operator/deploy/resources/kourier/download.sh
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  knative-operator/deploy/resources/kourier/kourier-v0.3.10.yaml
  knative-operator/pkg/common/openshift.go
  knative-operator/pkg/common/openshift_test.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/webhook/knativeserving/webhook_mutating.go
  test/lib.bash
Labels: approved, lgtm, size/L
