Repository openshift-knative/serverless-operator, pull requests merged in 2020-09, with the labels that each got.

#420 Scale up workers only for upstream E2E tests
  hack/lib/scaleup.bash
  test/upstream-e2e-tests.sh
Labels: approved

#421 Include test workaround for SRVCOM-1008
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#417 updating to kn-client 0.15.2
  olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm

#415 SRVKE-411 Override webhook resource request/limit with S-O
  knative-operator/pkg/common/eventing.go
  knative-operator/pkg/common/eventing_test.go
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/util.go
Labels: approved, lgtm

#418 SRVKS-592 TestKsvcWithServiceMeshSidecar
  test/service.go
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#424 cluster-local variants of the servicemesh test
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#425 separate servicemesh and serverless installs
  Makefile
  README.md
  test/lib.bash
Labels: approved, lgtm

#388 [SRVKS-495] Add readiness metrics and dashboard
  knative-operator/cmd/manager/main.go
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-health.yaml
  knative-operator/deploy/role_service_monitor.yaml
  knative-operator/pkg/common/constants.go
  knative-operator/pkg/common/health_dashboard.go
  knative-operator/pkg/common/metrics.go
  knative-operator/pkg/common/monitoring.go
  knative-operator/pkg/common/monitoring_test.go
  knative-operator/pkg/common/service_monitor.go
  knative-operator/pkg/common/testdata/role_service_monitor.yaml
  knative-operator/pkg/controller/add_healthdashboard.go
  knative-operator/pkg/controller/healthdashboard/healthdashboard_controller.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/dashboard/dashboard.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#423 Migrate master to the new bundle format
  .gitignore
  README.md
  hack/catalog.sh
  hack/lib/catalogsource.bash
  hack/lib/serverless.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/1.4.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.4.1/serverless-operator.v1.4.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.4.1/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.5.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.5.0/serverless-operator.v1.5.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.5.0/serving_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.6.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.6.0/serverless-operator.v1.6.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.7.1/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.7.1/serverless-operator.v1.7.1.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/1.8.0/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/1.8.0/serverless-operator.v1.8.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/container.yaml
  olm-catalog/serverless-operator/index.Dockerfile
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/metadata/annotations.yaml
  olm-catalog/serverless-operator/serverless-operator.package.yaml
  test/serving.bash
Labels: approved, lgtm

#430 Document image replacement and fix operator image ref.
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#431 SRVKS-595 TestKsvcWithServiceMeshJWTDefaultPolicy
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#433 fix ctx.T not referencing current testing.T
  test/clients.go
Labels: approved, lgtm

#434 fix rerunning servicemesh test
  test/Gopkg.lock
  test/servinge2e/servicemesh_test.go
  test/vendor/knative.dev/pkg/test/helpers/dir.go
  test/vendor/knative.dev/pkg/test/helpers/dryrun.go
  test/vendor/knative.dev/pkg/test/helpers/error.go
  test/vendor/knative.dev/pkg/test/helpers/name.go
Labels: approved, lgtm

#427 Use spec.rule.Visibility instead of spec.Visibility in KIngress
  serving/ingress/pkg/controller/ingress/ingress_controller.go
  serving/ingress/pkg/controller/ingress/resources/route.go
  serving/ingress/pkg/controller/ingress/resources/route_test.go
Labels: approved, lgtm

#440 Fix olm for health dashboard - master
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test

#445 Fixes based on Operator One Click Report
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#442 Fix olm for health dashboard - 1.9
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#446 Fixes based on Operator One Click Report
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#450 Replace value with image in relatedImages
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#451 Update .gitignore to exclude certificates created by hack/lib/mesh.bash
  .gitignore
Labels: approved, lgtm

#453 Fix labels
  olm-catalog/serverless-operator/Dockerfile
Labels: approved, lgtm

#455 Disable cr metrics port in master
  knative-operator/pkg/common/service_monitor.go
Labels: approved, lgtm, needs-ok-to-test

#454 Disable cr metrics port in 1.9
  knative-operator/pkg/common/service_monitor.go
Labels: approved, lgtm, needs-ok-to-test

#438 Bumping OLM to 1.10
  hack/lib/catalogsource.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#447 Stop using LoadBalancer in status field
  serving/ingress/pkg/controller/ingress/ingress_controller_test.go
  serving/ingress/pkg/controller/ingress/resources/route.go
  serving/ingress/pkg/controller/ingress/resources/route_test.go
Labels: approved, lgtm

#452 Fix typo in serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#459 Remove diff to avoid panic due to comparing unexported fields. (#385) - release-1.9
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#458 Remove diff to avoid panic due to comparing unexported fields. (#385) - master
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm

#462 Add olm.skipRange
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#456 Remove controller-runtime client where not necessary.
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/common/eventing.go
  knative-operator/pkg/common/eventing_test.go
  knative-operator/pkg/common/service_monitor.go
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/webhook/knativeeventing/webhook_mutating.go
Labels: approved, lgtm

#464 Mark nested vendor files as vendor to ignore the diffs in PRs.
  .gitattributes
Labels: approved, lgtm

#463 Add olm.skipRange to csv
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#469 Install yq in the build image for CI
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#468 Read CURRENT_CSV,PREVIOUS_CSV,OLM_CHANNEL from metadata
  hack/lib/vars.bash
Labels: approved

#457 Create serverless OperatorGroup only if there are no other operator g…
  hack/lib/namespaces.bash
Labels: approved, lgtm

#470 Drop liveness probe of serverless-index
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#428 Use env vars for KNATIVE_OPENSHIFT_INGRESS and KNATIVE_OPERATOR images
  hack/lib/catalogsource.bash
Labels: approved

#475 Fixing stupid wrong value name...should be image
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#476 Fail if yq is not on PATH
  hack/lib/vars.bash
Labels: approved, lgtm

#472 Initial KnativeKafka type and controller
  knative-operator/deploy/crds/operator_v1alpha1_knativekafka_crd.yaml
  knative-operator/deploy/role.yaml
  knative-operator/pkg/apis/addtoscheme_knative_operator_v1alpha1.go
  knative-operator/pkg/apis/addtoscheme_operator_v1alpha1.go
  knative-operator/pkg/apis/operator/group.go
  knative-operator/pkg/apis/operator/v1alpha1/doc.go
  knative-operator/pkg/apis/operator/v1alpha1/knativekafka_types.go
  knative-operator/pkg/apis/operator/v1alpha1/register.go
  knative-operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  knative-operator/pkg/controller/add_knativekafka.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
Labels: approved, lgtm

#480 Update requirements section in the README
  README.md
Labels: approved, lgtm

#483 Fixing the names of the actual deployments of 0.16
  test/e2e/knative_eventing_test.go
Labels: approved, lgtm

#484 Disable connection keep-alive in networkpolicy test
  test/servinge2e/verify_networkpolicy_test.go
Labels: approved, lgtm

#488 [SRVKS-628] Skip networkpolicy test until we fix it properly
  test/servinge2e/verify_networkpolicy_test.go
Labels: approved, lgtm

#478 Override image coordinates in upstream operator too
  olm-catalog/serverless-operator/generate_csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#477 Add a readiness probe that waits for the webhook to be up
  olm-catalog/serverless-operator/csv.template.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#485 NIT: Adding check for single pod deployments of serving
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#482 nit: align with the allow test
  test/servinge2e/verify_networkpolicy_test.go
Labels: approved, lgtm

#492 Revert "Add a readiness probe that waits for the webhook to be up"
  olm-catalog/serverless-operator/csv.template.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm
