Repository openshift-knative/serverless-operator, pull requests merged in 2021-06, with the labels that each got.

#940 Update Strimzi API version to v1beta2
  hack/lib/strimzi.bash
Labels: approved, lgtm, ok-to-test

#995 [SRVKS-744] Only configure domain template if not otherwise set
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/serving_test.go
  openshift-knative-operator/pkg/serving/extension.go
Labels: approved, lgtm

#961 Add `make install-full-mesh` to deploy mesh to test secure traffic
  Makefile
  README.md
  docs/full-mesh.md
  docs/mesh.md
  hack/lib/mesh.bash
  hack/lib/mesh_resources/gateway.yaml
  hack/lib/mesh_resources/peerauthentication.yaml
  hack/lib/mesh_resources/smcp.yaml
  hack/lib/mesh_resources/smmr.yaml
  hack/lib/mesh_resources/subscription.yaml
Labels: approved, lgtm

#997 [SRVKE-755] Update default value for Sinkbinding webhook to our OCP Serverless override
  olm-catalog/serverless-operator/hack/001-eventing-sinkbinding-default-override
  olm-catalog/serverless-operator/hack/update-manifests.sh
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeeventing_crd.yaml
Labels: approved, lgtm

#1001 [SRVKS-258] Test that even project admins can't create internal resources
  test/servinge2e/user_permissions_test.go
Labels: approved, lgtm

#1000 Add istio-webhook-certs secret
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/4-500-webhook-secret.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/5-config.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/6-controller.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/7-webhook-deployment.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/8-webhook-service.yaml
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#989 Update Exploring serverless apps quickstart text for connecting an event source to a knative service
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
Labels: approved, lgtm, ok-to-test

#998 [SRVCOM-1331] Secure metric endpoints for Kafka control plane pods
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  knative-operator/pkg/controller/knativekafka/rbacproxytransforms.go
  openshift-knative-operator/pkg/monitoring/helpers.go
  openshift-knative-operator/pkg/monitoring/monitoring_eventing.go
  openshift-knative-operator/pkg/monitoring/monitoring_serving.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection_test.go
  test/e2ekafka/knative_kafka_test.go
  test/monitoringe2e/helpers.go
Labels: approved, lgtm

#1003 Add knativekafka default to 2 replicas
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/apis/operator/v1alpha1/knativekafka_types.go
  knative-operator/pkg/common/kafka.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  knative-operator/pkg/webhook/knativekafka/webhook_mutating.go
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativekafka_crd.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1012 Add OCP 4.8
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#1010 Skip 0 replica optimization
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/001-eventing-kafkachannel_replicas1.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1005 [release-1.15] Update Exploring serverless apps quickstart text for connecting an event source to a knative service
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
Labels: approved, lgtm, ok-to-test

#1008 [RELEASE-1.15][SRVKE-838] Delete old broker filter,ingress sm names to avoid alerts during upgrades
  knative-operator/pkg/common/monitoring.go
Labels: approved, lgtm

#1009 [MAIN][SRVKE-838] Delete old broker filter,ingress sm names to avoid alerts during upgrades
  knative-operator/pkg/common/monitoring.go
Labels: approved, lgtm

#1019 Remove KafkaChannel before asserting correct deletion of objects
  test/e2ekafka/knative_kafka_test.go
Labels: approved, lgtm

#1015 Always use proxy to resolve dependencies to upgrade
  hack/update-deps.sh
Labels: approved, lgtm

#1018 Revert "Adding patch for 1 replica (#1010)"
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/001-eventing-kafkachannel_replicas1.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1020 [SRVCOM-1358] Fix getting started and installation links in CSV
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1021 [SRVCOM-1036] Use a more helpful description
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1022 OCP 4.6 was listed, which is kube 1.19
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#902 [ServiceMesh] Use secret instead of file mount for the certificates
  test/servicemesh.go
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#938 [release-1.14] SRVCOM-1282 Fix UI test failures from nightlies
  test/extensione2e/kafka/kafka_channel_ksvc_test.go
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/extensione2e/kafka/source_kafka_broker_ksvc_test.go
  test/ui/cypress/integration/serving.spec.js
Labels: approved, lgtm

#1017 Cleanup monitoring resource files
  knative-operator/deploy/resources/monitoring/role-service-monitor.yaml
  knative-operator/deploy/resources/monitoring/source-service-monitor.yaml
  knative-operator/deploy/resources/monitoring/source-service.yaml
  knative-operator/pkg/common/monitoring.go
  knative-operator/pkg/common/monitoring_test.go
  knative-operator/pkg/common/service_monitor.go
  knative-operator/pkg/common/sources/source_deployment_discovery_controller.go
  knative-operator/pkg/common/sources/source_deployment_discovery_controller_test.go
  knative-operator/pkg/common/testdata/role-service-monitor.yaml
  knative-operator/pkg/common/testdata/source-service-monitor.yaml
  knative-operator/pkg/common/testdata/source-service.yaml
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller_test.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved, lgtm

#1013 Drop knativekafka patching-out kafka-webhook-pdb
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/007-eventing-kafka-pdb.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1023 [SRVCOM-1285] Drop unsupported fields from the Serving CRD
  olm-catalog/serverless-operator/hack/002-serving-drop-unsupported-fields.patch
  olm-catalog/serverless-operator/hack/update-manifests.sh
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeserving_crd.yaml
Labels: approved, lgtm

#1028 Update client to v0.22.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#1025 Reduce privileges of test accounts
  test/serving.bash
Labels: approved, lgtm

#1027 [SRVKS-752] Add NetworkPolicy for webhook on net-istio ingress
  hack/lib/mesh_resources/smmr.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/0-webhook-servicemesh.yaml
  openshift-knative-operator/hack/007-webhook-servicemesh.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1026 Add patch to change kafka-webhook pdb to 1 (absolute value)
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/007-eventing-kafka-pdb.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1033 [RELEASE-1.15] [SRVCOM-1148] Add a 'stop' bundle image that can act as the first in the chain
  Makefile
  olm-catalog/serverless-operator/stopbundle.Dockerfile
  templates/stopbundle.Dockerfile
Labels: approved

#1029 Bump operator version to 0.22.0
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#1024 [SRVCOM-1148] Automatically use stop-image from previous version
  Makefile
  hack/lib/catalogsource.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/stopbundle.Dockerfile
  templates/stopbundle.Dockerfile
Labels: approved, lgtm

#1035 Drop unnecessary version check
  hack/lib/serverless.bash
Labels: approved, lgtm

#1032 SRVCOM-1375 Check Serverless alerts after tests
  test/e2e-tests.sh
  test/lib.bash
  test/upstream-e2e-tests.sh
Labels: approved, lgtm

#1036 [SRVKS-743] Disable monitoring if istio is enabled
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
Labels: approved, lgtm

#1038 Drop NetworkPolicy test
  test/lib.bash
  test/servinge2e/user_permissions_test.go
  test/servinge2e/verify_networkpolicy_test.go
Labels: approved, lgtm

#1031 [SRVCOM-1285] Drop unsupported fields from the Eventing CRD
  olm-catalog/serverless-operator/hack/003-eventing-drop-unsupported-fields.patch
  olm-catalog/serverless-operator/hack/update-manifests.sh
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativeeventing_crd.yaml
Labels: approved, lgtm

#1037 Rename `0-webhook-servicemesh.yaml` to `0-networkpolicy-mesh.yaml`
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/0-networkpolicy-mesh.yaml
  openshift-knative-operator/hack/007-networkpolicy-mesh.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1040 [SRVKS-696] Expose config-autoscaler for every user
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/2-serving-core.yaml
  openshift-knative-operator/hack/002-openshift-serving-role.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1039 Remove workaround in `wait_for_knative_serving_ingress_ns_deleted`
  test/lib.bash
  test/serving.bash
Labels: approved, lgtm

#1041 Update UI test deps
  test/ui/package-lock.json
  test/ui/package.json
Labels: approved, lgtm

#1045 Pull all manifests from upstream
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1042 Fix a few stray shellcheck errors
  hack/update-deps.sh
  test/eventing-kafka.bash
  test/eventing.bash
  test/lib.bash
Labels: approved, lgtm

#1047 Add kafka webhook deployment resources patch
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/008-eventing-kafka-webhook-resources.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1048 Drop HTTP_PROXY test
  test/e2e/knative_serving_test.go
Labels: approved, lgtm

#1049 [SRVKS-763] Explicitly default domain claim creation
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
Labels: approved, lgtm

#1050 Install ytt in the build image
  openshift/ci-operator/build-image/Dockerfile
  templates/build-image.Dockerfile
Labels: approved, lgtm

#1053 [SRVCOM-1416] Login test users without using a precreated KUBECONFIG
  hack/lib/catalogsource.bash
  test/lib.bash
Labels: approved, lgtm

#1054 [RELEASE-1.16] [SRVCOM-1416] Login test users without using a precreated KUBECONFIG
  hack/lib/catalogsource.bash
  test/lib.bash
Labels: approved, lgtm

#1056 Point CSV references to actual 1.16 images
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1057 Prepare main for moving forward with 1.17 development
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  olm-catalog/serverless-operator/stopbundle.Dockerfile
Labels: approved, lgtm

#1060 Stop deleting installplans explicitly
  hack/lib/serverless.bash
Labels: approved, lgtm

#1063 Fix indent in TestKsvcWithServiceMeshJWTDefaultPolicy
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#1058 [RELEASE-1.16][SRVKE-841] Fix long source name 1.16
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-resources.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-serving-resources.yaml
Labels: approved, lgtm

#1052 [Main][SRVKE-841] Fix source resources dashboard for long source names
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-resources.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-serving-resources.yaml
Labels: approved, lgtm

#1061 Remove scaling of workers
  test/upstream-e2e-tests.sh
Labels: approved, lgtm

#1064 Try Red Hat actions to install tools
  .github/workflows/validate.yaml
Labels: approved, lgtm

#1062 Do not clean up resources when test failed
  test/clients.go
Labels: approved, lgtm

#1066 [Main] Fix Knative dashboard tags in 4.8
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-broker.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-source.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-health.yaml
Labels: approved, lgtm

#1068 [UI tests] Await until 'Add Revision' button isn't disabled
  test/ui/cypress/integration/serving.spec.js
Labels: approved, lgtm

#1071 Increase timeout to login user to 10 minutes
  hack/lib/catalogsource.bash
  test/lib.bash
Labels: approved, lgtm

#1074 Filter out the pingsource alert
  test/lib.bash
Labels: approved, lgtm

#1067 [Release-1.16][Backport]Fix Knative dashboard tags for 4.8
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-broker.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-source.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-health.yaml
Labels: approved, lgtm

#1069 [QE][UI] Adding a cluster.local test case
  test/ui/cypress/integration/serving.spec.js
Labels: approved, lgtm
