Repository openshift-knative/serverless-operator, pull requests merged in 2021-07, with the labels that each got.

#1075 Add `--enable-alpha` option to ha test
  test/serving.bash
  test/v1alpha1/resources/operator.knative.dev_v1alpha1_knativeserving_cr.yaml
Labels: approved, lgtm

#1076 [1.16] Remove HPA for kafka webhook
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/001-eventing-kafka-hpa.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#1077 [SRVKS-775] Use mirrored maistra image from quay.io
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1080 Stop auto-upgrading Openshift related golang deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm

#1078 Update serverless-operator with secure traffic doc
  docs/full-mesh.md
Labels: approved, lgtm

#1079 Remove redundant type casting
  knative-operator/pkg/controller/dashboard/dashboard.go
Labels: approved, lgtm

#1043 [SRVKE-799] Channel visualization for the admin
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-channel.yaml
  knative-operator/pkg/controller/dashboard/dashboard.go
  knative-operator/pkg/controller/dashboard/testdata/grafana-dash-knative-eventing-channel.yaml
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller_test.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1081 UI tests OCP version-aware
  test/ui-e2e-tests.sh
  test/ui/cypress/integration/serving.spec.js
  test/ui/cypress/plugins/index.js
  test/ui/cypress/support/index.js
  test/ui/cypress/support/semver.js
  test/ui/package-lock.json
  test/ui/package.json
Labels: approved, lgtm

#1044 [SRVKE-873] Update eventing dashboards
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-broker.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-resources.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-eventing-source.yaml
  knative-operator/deploy/resources/dashboards/grafana-dash-knative-serving-resources.yaml
Labels: approved, lgtm

#1082 Cleanup and fixes
  knative-operator/pkg/common/deployment.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  serving/ingress/pkg/reconciler/ingress/ingress_test.go
  test/clients.go
  test/proxy.go
  test/service.go
  test/servicemesh.go
Labels: approved, lgtm

#1083 Remove all docker references (except zipkin)
  README.md
  knative-operator/pkg/common/eventing_test.go
  knative-operator/pkg/common/serving_test.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativekafka/images_test.go
  test/servinge2e/service_to_service_test.go
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#1084 [1.16] Backport UI tests recent changes
  test/ui-e2e-tests.sh
  test/ui/cypress/integration/serving.spec.js
  test/ui/cypress/plugins/index.js
  test/ui/cypress/support/index.js
  test/ui/cypress/support/semver.js
  test/ui/package-lock.json
  test/ui/package.json
Labels: approved, lgtm

#1086 Improve dashboard code
  knative-operator/deploy/resources/dashboards/eventing/grafana-dash-knative-eventing-broker.yaml
  knative-operator/deploy/resources/dashboards/eventing/grafana-dash-knative-eventing-channel.yaml
  knative-operator/deploy/resources/dashboards/eventing/grafana-dash-knative-eventing-resources.yaml
  knative-operator/deploy/resources/dashboards/eventing/grafana-dash-knative-eventing-source.yaml
  knative-operator/deploy/resources/dashboards/serving/grafana-dash-knative-serving-resources.yaml
  knative-operator/pkg/common/health_dashboard.go
  knative-operator/pkg/controller/dashboard/dashboard.go
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-broker.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-channel.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-resources.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-source.yaml
  knative-operator/pkg/controller/dashboard/testdata/serving/grafana-dash-knative-serving-resources.yaml
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller_test.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1094 Revert "Try Red Hat actions to install tools (#1064)"
  .github/workflows/validate.yaml
Labels: approved

#1095 Target correct containers in csv generation
  hack/generate/csv.sh
Labels: approved, lgtm

#1093 Use 'Always' PullPolicy for all images to ease development
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1090 Refactor monitoring files and dirs
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/controller/add_healthdashboard.go
  knative-operator/pkg/controller/add_sourcedeploydiscovery.go
  knative-operator/pkg/controller/dashboard/testdata/broker-service-monitors.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-broker.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-channel.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-resources.yaml
  knative-operator/pkg/controller/dashboard/testdata/eventing/grafana-dash-knative-eventing-source.yaml
  knative-operator/pkg/controller/dashboard/testdata/role-service-monitor.yaml
  knative-operator/pkg/controller/dashboard/testdata/serving/grafana-dash-knative-serving-resources.yaml
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller_test.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  knative-operator/pkg/monitoring/dashboards/health/healthdashboard_controller.go
  knative-operator/pkg/monitoring/dashboards/health/serverless_health_dashboard_setup.go
  knative-operator/pkg/monitoring/dashboards/knative_dashboard_setup.go
  knative-operator/pkg/monitoring/health_metrics.go
  knative-operator/pkg/monitoring/kafka_rbacproxy_transforms.go
  knative-operator/pkg/monitoring/monitoring.go
  knative-operator/pkg/monitoring/monitoring_test.go
  knative-operator/pkg/monitoring/sources/source_deployment_discovery_controller.go
  knative-operator/pkg/monitoring/sources/source_deployment_discovery_controller_test.go
  knative-operator/pkg/monitoring/sources/source_service_monitor.go
  openshift-knative-operator/pkg/monitoring/helpers_test.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection_test.go
  openshift-knative-operator/pkg/monitoring/testdata/rbac-proxy.yaml
  openshift-knative-operator/pkg/monitoring/testdata/rbac.yaml
  openshift-knative-operator/pkg/monitoring/testdata/serving-core-deployment.yaml
Labels: approved, lgtm

#1097 [QE] Retry the flaky UI tests
  test/ui/cypress.json
Labels: approved, lgtm

#1014 Run upstream e2e test with net-istio
  Makefile
  hack/lib/serverless.bash
  hack/lib/vars.bash
  test/serving.bash
  test/upstream-e2e-tests.sh
Labels: approved, lgtm

#1092 Serve CLI artifacts from the operator deployment rather than a ksvc
  hack/generate/csv.sh
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
  olm-catalog/serverless-operator/manifests/knative-operator.service.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
  test/servinge2e/verify_deploy_resources_test.go
Labels: approved, lgtm

#1102 Add openshift-cherrypick-robot to approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#1105 Explicitly set controller deployment name to distinguish Serving and Kourier controller image
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1096 Use of ocp range feature
  hack/generate/csv.sh
  hack/generate/dockerfile.sh
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/project.yaml
  olm-catalog/serverless-operator/stopbundle.Dockerfile
Labels: approved, lgtm, ok-to-test

#1107 [SRVKS-779] Add dashboard for knative service queue proxy metrics
  knative-operator/deploy/resources/dashboards/serving/grafana-dash-knative-serving-queue-proxy.yaml
Labels: approved, lgtm

#1113 Add yq to local bin
  .github/workflows/validate.yaml
Labels: approved, lgtm

#1110 Reorder fields in the CSV to group better
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1111 [SRVCOM-1432] Drop unnecessary permissions
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1117 [SRVCOM-1432] Drop namespace local permissions
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1119 Wait for objects to be deleted in user permission tests
  test/eventinge2e/user_permissions_test.go
  test/extensione2e/kafka/user_permissions_test.go
  test/servinge2e/user_permissions_test.go
Labels: approved, lgtm

#1112 [SRVCOM-1432] Be explicit about the permissions required
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1118 Deduplicate test kernel for permission tests
  test/eventinge2e/user_permissions_test.go
  test/extensione2e/kafka/user_permissions_test.go
  test/servinge2e/user_permissions_test.go
  test/user_permissions.go
Labels: approved, lgtm

#1123 Verify the deletion of the object when it is allowed
  test/user_permissions.go
Labels: approved, lgtm

#1108 Use prettier to consistently format the CSV
  .github/workflows/validate.yaml
  Makefile
  README.md
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1121 Serve CLI artifacts from operator
  hack/generate/csv.sh
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1116 [UI] Remove skip version TODO
  test/ui/cypress/integration/serving.spec.js
Labels: approved, lgtm

#1085 Run downstream test with net-istio & mTLS
  Makefile
  hack/lib/mesh_resources/smcp.yaml
  hack/lib/mesh_resources/smmr.yaml
  hack/lib/serverless.bash
  openshift-knative-operator/cmd/operator/kodata/ingress/0.23/0-networkpolicy-mesh.yaml
  openshift-knative-operator/hack/007-networkpolicy-mesh.patch
  test/e2e-tests.sh
  test/lib.bash
  test/service.go
  test/servinge2e/helpers.go
  test/servinge2e/kourier/custom_route_test.go
  test/servinge2e/kourier/helpers.go
  test/servinge2e/kourier/service_to_service_test.go
  test/servinge2e/kourier/servicemesh_test.go
  test/servinge2e/kourier/verify_http_and_https_test.go
  test/servinge2e/kourier/verify_route_conflict_test.go
  test/servinge2e/user_permissions_test.go
Labels: approved, lgtm

#1124 Adding a conditional skip for UI tests until SRVKS-782 is fixed
  test/ui-e2e-tests.sh
Labels: approved, lgtm

#1120 [SRVCOM-1433] Employ basic security measures for all s-o containers
  knative-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
  templates/csv.yaml
Labels: approved, lgtm
