Repository openshift-knative/serverless-operator, pull requests merged in 2021-05, with the labels that each got.

#927 Deduplicate a few occurrences of constants in code
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
  serving/ingress/pkg/reconciler/ingress/ingress_test.go
Labels: approved, lgtm

#922 Try to enable conformance tests for eventing
  test/eventing.bash
Labels: approved, lgtm

#913 Automate knativekafka manifest update in hack/update-manifests.sh, update knativekafka to v0.21.1
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/deploy/resources/knativekafka/2-source.yaml
  knative-operator/deploy/resources/knativekafka/README.md
  knative-operator/deploy/resources/knativekafka/kafkachannel-latest.yaml
  knative-operator/deploy/resources/knativekafka/kafkachannel-v0.20.0.yaml
  knative-operator/deploy/resources/knativekafka/kafkasource-latest.yaml
  knative-operator/deploy/resources/knativekafka/kafkasource-v0.20.0.yaml
  knative-operator/deploy/resources/knativekafka/manifest_test.go
  knative-operator/hack/006-kafkachannel-storage-beta1.patch
  knative-operator/hack/update-manifests.sh
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  knative-operator/pkg/controller/knativekafka/testdata/1-channel-consolidated.yaml
  knative-operator/pkg/controller/knativekafka/testdata/2-source.yaml
  knative-operator/pkg/controller/knativekafka/testdata/kafkachannel-latest.yaml
  knative-operator/pkg/controller/knativekafka/testdata/kafkasource-latest.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/hack/update-manifests.sh
  openshift/ci-operator/source-image/Dockerfile
  templates/csv.yaml
Labels: approved, lgtm

#929 Update client to v0.21.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#928 Bump versions for 1.10.2
  hack/lib/catalogsource.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#930 manually Adding post-install for eventing
  knative-operator/deploy/resources/knativekafka/3-eventing-kafka-post-install.yaml
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#888 [SRVCOM-1237] Backport 836
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/common/monitoring.go
  knative-operator/pkg/common/monitoring_test.go
Labels: lgtm

#871 svc.ci -> ci for release-1.11
  hack/generate/csv.sh
  hack/lib/catalogsource.bash
  hack/lib/strimzi.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift/ci-operator/source-image/Dockerfile
  templates/csv.yaml
  templates/test-source-image.Dockerfile
  test/eventing-contrib.bash
  test/eventing.bash
  test/serving.bash
  test/servinge2e/servicemesh_test.go
Labels: approved, lgtm

#918 Adding eventing pdb patch
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.21.0/2-eventing-core.yaml
  openshift-knative-operator/hack/006-eventing-pdb.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#933 poke CI to promote 1.14.1 bundle
  ci
Labels: approved, lgtm

#932 hotfix, add 1.14.0 bundle from quay
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#937 Drop unnecessary file removals
  hack/update-deps.sh
Labels: approved, lgtm

#942 [main] Going with hard coded 0.22.1 version for 1.15
  hack/lib/strimzi.bash
Labels: approved, lgtm

#950 Remove arm64 link from consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  test/servinge2e/verify_deploy_resources_test.go
Labels: approved, lgtm

#951 Remove arm64 link from consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  test/servinge2e/verify_deploy_resources_test.go
Labels: approved, lgtm

#943 [1.11] Going with 0.22.1 of Strimzi
  hack/lib/strimzi.bash
Labels: approved, lgtm

#944 [1.12] Going with 0.22.1 of Strimzi
  hack/lib/strimzi.bash
Labels: approved, lgtm

#945 [1.13] Going with 0.22.1 of Strimzi
  hack/lib/strimzi.bash
Labels: approved, lgtm

#946 [1.14] Going with 0.22.1 of Strimzi
  hack/lib/strimzi.bash
Labels: approved, lgtm

#954 Drop 1.14.1 bundle
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#948 Run ./hack/update-deps.sh --upgrade
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: approved, lgtm

#949 Add upgrade build tag to golangci-lint config
  .golangci.yaml
Labels: approved, lgtm

#958 [RELEASE-1.15] Drop 1.14.1 bundle
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#947 Bump general and serving golang deps to 0.22
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/operator/pkg/client/injection/client/client.go
  vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  vendor/knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/operator/pkg/reconciler/common/ha.go
  vendor/knative.dev/operator/pkg/reconciler/common/releases.go
  vendor/knative.dev/operator/pkg/reconciler/common/stages.go
  vendor/knative.dev/operator/pkg/reconciler/common/testing/util.go
  vendor/knative.dev/operator/pkg/reconciler/knativeeventing/knativeeventing.go
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/ingress/kourier.go
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/test/upgrade/README.md
  vendor/modules.txt
Labels: approved, lgtm

#962 [main] Updating vendor deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm

#953 bump to 1.16
  hack/lib/catalogsource.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#959 Update Knative Serving to 0.22.0
  knative-operator/deploy/resources/kourier/kourier-latest.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/1-200-clusterrole.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/2-500-mutating-webhook.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/3-500-validating-webhook.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/4-config.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/5-controller.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/6-webhook-deployment.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/7-webhook-service.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/4-serving-domainmapping-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/5-serving-domainmapping.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/6-serving-post-install-jobs.yaml
  openshift-knative-operator/hack/003-serving-pdb.patch
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#966 [RELEASE-1.15] Fix 1.15 references
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, do-not-merge/hold, lgtm

#965 Updating the Knative Eventing manifiests to 0.22.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/1-eventing-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/3-in-memory-channel.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/4-mt-channel-broker.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/5-eventing-sugar-controller.yaml
  openshift-knative-operator/hack/002-openshift-eventing-role.patch
  openshift-knative-operator/hack/005-disable-hpa.patch
  openshift-knative-operator/hack/006-eventing-pdb.patch
  openshift-knative-operator/hack/update-manifests.sh
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#967 Update to kafkas 0.22.3
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/deploy/resources/knativekafka/2-source.yaml
  knative-operator/hack/006-kafkachannel-storage-beta1.patch
  knative-operator/hack/update-manifests.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#964 [Release 1.15] Fix rbac proxy images for Eventing
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#971 Determine default ingress class based on enabled ingress
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
  openshift-knative-operator/pkg/serving/ingress.go
  openshift-knative-operator/pkg/serving/ingress_test.go
  openshift-knative-operator/pkg/serving/kourier.go
Labels: approved, lgtm

#974 Update woke to 0.8.0
  .github/workflows/validate.yaml
Labels: approved, lgtm

#975 Fix stray shellcheck warnings to make everything clear
  .github/workflows/validate.yaml
  test/eventing.bash
Labels: approved, lgtm

#978 [RELEASE-1.15] Fix kube-rbac references in the CSV
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#977 [1.15] Remove pdbs eventings and kafkas
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/007-eventing-kafka-pdb.patch
  knative-operator/hack/update-manifests.sh
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.21.0/2-eventing-core.yaml
  openshift-knative-operator/hack/006-eventing-pdb.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#970 Apply kourier defaulting a bit more diligently
  openshift-knative-operator/pkg/serving/extension_test.go
  openshift-knative-operator/pkg/serving/ingress.go
Labels: approved, lgtm

#973 Replace golint with revive
  .github/workflows/validate.yaml
  .golangci.yaml
  knative-operator/pkg/common/service_monitor.go
  knative-operator/pkg/common/serving.go
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/webhook/knativeeventing/webhook_mutating.go
  knative-operator/pkg/webhook/knativeeventing/webhook_validating.go
  knative-operator/pkg/webhook/knativekafka/webhook_validating.go
  knative-operator/pkg/webhook/knativeserving/webhook_mutating.go
  knative-operator/pkg/webhook/knativeserving/webhook_validating.go
  openshift-knative-operator/pkg/common/deployment.go
  openshift-knative-operator/pkg/eventing/extension.go
  openshift-knative-operator/pkg/serving/extension.go
  test/clients.go
Labels: approved, lgtm

#963 Fix rbac proxy images for Eventing
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection_test.go
Labels: approved, lgtm

#976 Update operator-sdk to 1.7.2
  .github/workflows/validate.yaml
Labels: approved, lgtm

#980 Fix a few misspellings
  hack/lib/metadata.bash
  hack/lib/serverless.bash
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
  test/eventing-kafka.bash
Labels: approved, lgtm

#919 Setting the Eventing HA to 2, like we have for serving
  knative-operator/pkg/common/eventing.go
  knative-operator/pkg/common/eventing_test.go
  openshift-knative-operator/pkg/eventing/extension.go
  openshift-knative-operator/pkg/eventing/extension_test.go
  test/e2e/knative_eventing_test.go
Labels: approved, lgtm

#982 [Trivial] Fix error message specifying knative eventing unsupported namespace
  openshift-knative-operator/pkg/eventing/extension.go
Labels: approved, lgtm

#981 Add misspell to our presubmit linters
  .github/workflows/validate.yaml
  Makefile
  README.md
Labels: approved, lgtm

#960 [SRVCOM-1329] Add metrics for openshift knative operator and ingress
  olm-catalog/serverless-operator/manifests/config-observability.yaml
  olm-catalog/serverless-operator/manifests/knative-openshift-ingress.service.yaml
  olm-catalog/serverless-operator/manifests/knative-openshift-ingress.servicemonitor.yaml
  olm-catalog/serverless-operator/manifests/openshift-knative-operator.service.yaml
  olm-catalog/serverless-operator/manifests/openshift-knative-operator.servicemonitor.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
  test/monitoringe2e/helpers.go
  test/monitoringe2e/monitoring_test.go
Labels: approved, lgtm

#985 Port kafkas pdb removal to main
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/007-eventing-kafka-pdb.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#984 [1.15] remove hpa for kafkas
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/hack/008-eventing-kafka-hpa.patch
  knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#988 [1.15] Adding some entry for the kafka migrator image
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#992 Revert "manually Adding post-install for eventing (#930)"
  knative-operator/deploy/resources/knativekafka/3-eventing-kafka-post-install.yaml
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#987 Destroy all image references to guarantee overrides to work
  hack/lib/common.bash
  knative-operator/deploy/resources/knativekafka/1-channel-consolidated.yaml
  knative-operator/deploy/resources/knativekafka/2-source.yaml
  knative-operator/hack/update-manifests.sh
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/5-controller.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/6-webhook-deployment.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/0.22/kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/3-in-memory-channel.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/4-mt-channel-broker.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/5-eventing-sugar-controller.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/5-serving-domainmapping.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/6-serving-post-install-jobs.yaml
  openshift-knative-operator/hack/update-manifests.sh
  openshift-knative-operator/pkg/testdata/serving-core-deployment.yaml
Labels: approved, lgtm

#990 Go with 2.7.0 of Apache Kafka
  hack/lib/strimzi.bash
Labels: approved, lgtm

#994 [SRVKS-741] Drop namespaces from manifests to prevent reconcilation
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/0.22.0/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/0.22.0/2-serving-core.yaml
  openshift-knative-operator/hack/001-eventing-namespace-deletion.patch
  openshift-knative-operator/hack/001-serving-namespace-deletion.patch
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm
