Repository openshift-knative/serverless-operator, pull requests merged in 2022-10, with the labels that each got.

#1727 Restricted pod admission policy for Zipkin pod
  hack/lib/strimzi.bash
  hack/lib/tracing.bash
Labels: approved, lgtm

#1739 [release-1.25] Update eventing-kafka-broker dependency
  go.mod
  go.sum
  vendor/github.com/klauspost/compress/.gitignore
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/huff0/bitreader.go
  vendor/github.com/klauspost/compress/huff0/compress.go
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.go
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.s
  vendor/github.com/klauspost/compress/huff0/decompress_generic.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo_amd64.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo_amd64.s
  vendor/github.com/klauspost/compress/zstd/README.md
  vendor/github.com/klauspost/compress/zstd/bitreader.go
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/bytebuf.go
  vendor/github.com/klauspost/compress/zstd/decoder.go
  vendor/github.com/klauspost/compress/zstd/decoder_options.go
  vendor/github.com/klauspost/compress/zstd/encoder.go
  vendor/github.com/klauspost/compress/zstd/encoder_options.go
  vendor/github.com/klauspost/compress/zstd/framedec.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder.go
  vendor/github.com/klauspost/compress/zstd/history.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
  vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
  vendor/github.com/klauspost/compress/zstd/zip.go
  vendor/github.com/klauspost/compress/zstd/zstd.go
  vendor/github.com/magiconair/properties/.gitignore
  vendor/github.com/magiconair/properties/.travis.yml
  vendor/github.com/magiconair/properties/CHANGELOG.md
  vendor/github.com/magiconair/properties/LICENSE.md
  vendor/github.com/magiconair/properties/README.md
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/kafka/data_plane_config.go
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/kafka/topic.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/addressable/send.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/kafka/verify_num_partitions_replication.go
  vendor/modules.txt
Labels: approved, lgtm

#1752 Bump deps to 1.5
  go.mod
  go.sum
  hack/update-deps.sh
  test/servinge2e/kourier/service_to_service_test.go
  test/servinge2e/kourier/servicemesh_test.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/labels.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/knative.dev/serving/test/util.go
  vendor/modules.txt
Labels: approved, lgtm

#1734 Use new multiarch variant for helloworld-go and hello-openshift images
  test/eventinge2e/source_to_ksvc_test.go
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/kitchensinke2e/ksvc/ksvc.go
  test/servinge2e/helpers.go
  test/servinge2e/kourier/helpers.go
  test/servinge2e/kourier/servicemesh_test.go
Labels: approved, lgtm

#1750 Separate upgrade and downgrade tests
  test/flags.go
  test/lib.bash
  test/upgrade/upgrade_test.go
Labels: approved, lgtm

#1754 Bump Knative operator manifests to 1.5.2
  olm-catalog/serverless-operator/hack/004-eventing-drop-unsupported-sources.patch
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#1756 Document migration from productized operator midstream operator
  docs/migrating-from-product-to-midstream.md
Labels: approved, lgtm

#1758 Use queue-sidecar-image instead of queueSidecarImage.
  hack/lib/common.bash
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.5.0/2-serving-core.yaml
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
Labels: approved, lgtm

#1674 [SRVKE-1076] Run eventing-kafka-broker e2e tests in SO
  Makefile
  hack/lib/strimzi.bash
  hack/lib/vars.bash
  test/config/eventing/kafka-broker-default-patch-rollback.yaml
  test/config/eventing/kafka-broker-default-patch.yaml
  test/eventing-kafka.bash
Labels: approved, lgtm

#1760 [release-1.25][SRVOCF-470] Add missing images for func to OLM
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1765 Adding most simple logging enhancement
  knative-operator/pkg/apis/operator/v1alpha1/knativekafka_types.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  olm-catalog/serverless-operator/manifests/operator_v1alpha1_knativekafka_crd.yaml
Labels: approved, lgtm

#1768 [release-1.25] Add s2i related images for func s2i to OLM
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm, do-not-merge/hold

#1769 [release-1.25] [SRVKE-1324] Avoid reconciliation loops (#1755)
  go.mod
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  openshift-knative-operator/pkg/monitoring/helpers.go
Labels: approved

#1770 [release-1.24] [SRVKE-1324] Avoid reconciliation loops (#1755)
  go.mod
  knative-operator/pkg/common/constants.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  openshift-knative-operator/pkg/common/deployment.go
  openshift-knative-operator/pkg/monitoring/helpers.go
Labels: approved, lgtm

#1747 Updating to latest Strimzi and Apache Kafka 3.2.3
  hack/lib/strimzi.bash
  hack/lib/vars.bash
Labels: approved, lgtm
