Repository openshift-knative/serverless-operator, pull requests merged in 2023-01, with the labels that each got.

#1901 Upgrade eventing-kafka version to latest midstream 1.1
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm

#1906 Disable/enable namespaced controllers as well, based on KnativeKafka spec.broker.enabled
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
Labels: approved, lgtm

#1910 Add istio label to knative-local-gateway service
  hack/lib/mesh_resources/gateway.yaml
Labels: approved, lgtm

#1918 Include workflow_dispatch to set current version
  .github/workflows/validate.yaml
Labels: approved

#1867 make eventinge2e verify the events were received
  Makefile
  hack/lib/vars.bash
  test/eventinge2e/eventing_to_ksvc_utils.go
  test/eventinge2e/source_broker_ksvc.go
  test/eventinge2e/source_broker_ksvc_test.go
  test/eventinge2e/source_channel_ksvc.go
  test/eventinge2e/source_channel_ksvc_test.go
  test/eventinge2e/source_to_ksvc_test.go
  test/extensione2e/kafka/kafka_channel_ksvc_test.go
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/extensione2e/kafka/source_kafka_broker_ksvc_test.go
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
  test/images.go
  test/lib.bash
  test/service.go
Labels: approved, lgtm

#1926 release 1.27 e2e eventing fix backport
  hack/lib/vars.bash
  test/eventinge2e/eventing_to_ksvc_utils.go
  test/eventinge2e/source_broker_ksvc.go
  test/eventinge2e/source_broker_ksvc_test.go
  test/eventinge2e/source_channel_ksvc.go
  test/eventinge2e/source_channel_ksvc_test.go
  test/eventinge2e/source_to_ksvc_test.go
  test/extensione2e/kafka/kafka_channel_ksvc_test.go
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/extensione2e/kafka/source_kafka_broker_ksvc_test.go
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
  test/images.go
  test/lib.bash
  test/service.go
Labels: approved, lgtm

#1915 Run namespaced broker upgrade tests
  go.mod
  go.sum
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
  test/upgrade/upgrade_test.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/broker/broker.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual/broker.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual/types.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/postdowngrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/postupgrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/preupgrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/smoke.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/suite.go
  vendor/modules.txt
Labels: approved, lgtm

#1916 [release-1.27] Upgrade tests and E2E for namespaced broker
  go.mod
  go.sum
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
  test/upgrade/upgrade_test.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/broker/broker.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/run.go
  vendor/knative.dev/eventing-kafka-broker/test/pkg/testing/auth.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual/broker.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/continual/types.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/postdowngrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/postupgrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/preupgrade.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/smoke.go
  vendor/knative.dev/eventing-kafka-broker/test/upgrade/suite.go
  vendor/modules.txt
Labels: approved, lgtm

#1890 [SRVCOM-2209] Support kube rbac proxy overrides
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  knative-operator/pkg/monitoring/kafka_rbacproxy_transforms.go
  openshift-knative-operator/pkg/monitoring/helpers.go
  openshift-knative-operator/pkg/monitoring/monitoring_eventing.go
  openshift-knative-operator/pkg/monitoring/monitoring_serving.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection_test.go
Labels: approved, lgtm

#1929 [SRVKE-1388] Namespaced Broker deletion hangs with foreground propagation policy
  knative-operator/pkg/monitoring/monitoring_kafka.go
  knative-operator/pkg/monitoring/monitoring_kafka_test.go
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
Labels: approved, lgtm

#1931 [RELEASE 1.27] Revert "add support for net-kourier secret filtering informer (#1764)"
  openshift-knative-operator/pkg/serving/istio.go
  openshift-knative-operator/pkg/serving/secretinformerfiltering.go
  openshift-knative-operator/pkg/serving/secretinformerfilterting_test.go
Labels: approved, lgtm

#1925 Watch KnativeEventing in KnativeKafka reconciler
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
Labels: approved, lgtm

#1927 [RELEASE-1.27] Add example for v1alpha1 to avoid scorecard warnings
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1928 Add example for v1alpha1to avoid scorecard warnings
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#1934 Increase receiver teardown to 10 seconds
  test/upgrade/continual/channel-config.toml
  test/upgrade/continual/kafka-broker-config.toml
  test/upgrade/continual/kafka-sink-source-config.toml
Labels: approved, lgtm

#1936 [RELEASE-1.27] [SRVKS-1013] make generated-files
  openshift-knative-operator/cmd/operator/kodata/ingress/1.6/0-kourier.yaml
Labels: approved, lgtm

#1859 :bug: [QE] Serverless is default for 4.12+ so UI tests no longer need to choose Serverless type
  test/ui/cypress/code/knative/serving/showcase.js
Labels: approved, lgtm

#1939 Add myself as an owner
  OWNERS_ALIASES
Labels: approved, lgtm

#1921 [release-1.27] :bug: [QE] Serverless is default for 4.12+ so UI tests no longer need to choose Serverless type
  test/ui/cypress/code/knative/serving/showcase.js
Labels: approved, lgtm

#1938 Revert change to RoleBinding from ClusterRoleBinding for a dataplane role
  knative-operator/pkg/monitoring/monitoring_kafka.go
  knative-operator/pkg/monitoring/monitoring_kafka_test.go
Labels: approved, lgtm

#1933 Bump Maistra 2.3 image for test
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#1943 Using 0.33 of Strimzi
  hack/lib/vars.bash
Labels: approved, lgtm

#1948 Create Secret for kitchensink tests
  test/lib.bash
Labels: approved, lgtm

#1946 :gift: Switch to quay.io/openshift-knative/showcase images
  test/ui/cypress/code/knative/serving/showcase.js
Labels: enhancement, approved, lgtm
