Repository openshift-knative/serverless-operator, pull requests merged in 2023-09, with the labels that each got.

#2254 Fix upgrade tests with ServiceMesh
  Makefile
  hack/lib/mesh_resources/authorization-policies/helm/eventing-e2e0.yaml
  hack/lib/mesh_resources/authorization-policies/helm/eventing-e2e1.yaml
  hack/lib/mesh_resources/authorization-policies/helm/eventing-e2e2.yaml
  hack/lib/mesh_resources/authorization-policies/helm/eventing-e2e3.yaml
  hack/lib/mesh_resources/authorization-policies/helm/eventing-e2e4.yaml
  test/upgrade/upgrade_test.go
Labels: approved, lgtm

#2263 Update gitops
  docs/gitops/README.md
  docs/gitops/gitops-subscription.yaml
Labels: approved, lgtm

#2259 SRVKE-1494: Install KEDA for testing
  Makefile
  hack/keda.sh
  hack/lib/__sources__.bash
  hack/lib/keda.bash
  hack/lib/keda_resources/kedacontroller.yaml
  hack/lib/keda_resources/subscription.yaml
Labels: approved, lgtm, jira/valid-reference

#2266 Better proposed APIs desc
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#2271 fix spelling errors
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  knative-operator/pkg/monitoring/dashboards/health/healthdashboard_controller.go
  knative-operator/pkg/monitoring/sources/source_deployment_discovery_controller.go
  openshift-knative-operator/pkg/monitoring/helpers.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection_test.go
  openshift-knative-operator/pkg/serving/kourier.go
  openshift-knative-operator/pkg/serving/secretinformerfilterting_test.go
  serving/ingress/pkg/reconciler/ingress/resources/route.go
Labels: approved, lgtm, ok-to-test

#2261 Use v1beta1 DomainMapping CRD
  serving/metadata-webhook/cmd/webhook/main.go
  serving/metadata-webhook/pkg/defaults/domainmapping_defaults.go
  serving/metadata-webhook/pkg/defaults/domainmapping_defaults_test.go
  test/service.go
  test/servinge2e/kourier/custom_route_test.go
  test/servinge2e/kourier/helpers.go
Labels: approved, lgtm

#2273 chore: Bumping Strimzi to next
  hack/lib/vars.bash
Labels: approved, lgtm

#2279 Fix typo in metadata-webhook
  serving/metadata-webhook/cmd/webhook/main.go
Labels: approved, lgtm

#2277 Fix upgrade sequence for kitchensink tests
  Makefile
  hack/lib/serverless.bash
  olm-catalog/serverless-operator/project.yaml
  test/installplan.go
  test/lib.bash
  test/upgrade/installation/serverless.go
  test/upgrade/kitchensink/kitchensink_test.go
Labels: approved, lgtm

#2284 Specify --channel param for upgrade tests
  test/lib.bash
Labels: approved, lgtm

#2283 [release-1.30] Update operator version to 1.30.1
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm
