Repository openshift-knative/serverless-operator, pull requests merged in 2023-05, with the labels that each got.

#2066 Add dsimansk to approvers list
  OWNERS_ALIASES
Labels: approved, lgtm

#2064 Rename channel name as per recommendation
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/metadata/annotations.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2070 Image template for Serving points to multiarch images
  hack/lib/vars.bash
Labels: approved, lgtm

#2076 Introduce bump SO automation
  .github/workflows/bump.yaml
  go.mod
  go.sum
  hack/cmd/bumpso/bumpso.go
  olm-catalog/serverless-operator/project.yaml
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/modules.txt
Labels: approved

#2077 Install YQ in bump SO automation
  .github/workflows/bump.yaml
Labels: approved

#2079 Run Bump SO automation only when branch is created or manually triggered
  .github/workflows/bump.yaml
Labels: approved

#2082 Increase scale for EKB tests to 5
  Makefile
Labels: approved, lgtm

#2086 Align go version in GH actions
  .github/workflows/validate.yaml
Labels: approved, lgtm

#2075 Bump eventing components to 1.9
  knative-operator/deploy/resources/knativekafka/broker/eventing-kafka-broker.yaml
  knative-operator/deploy/resources/knativekafka/channel/eventing-kafka-channel.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  knative-operator/deploy/resources/knativekafka/sink/eventing-kafka-sink.yaml
  knative-operator/deploy/resources/knativekafka/source/eventing-kafka-source.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/1-eventing-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/3-in-memory-channel.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/4-mt-channel-broker.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/5-eventing-post-install.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#2090 Bumping Strimzi to next
  hack/lib/vars.bash
Labels: approved, lgtm

#2091 Add install cert-manager operator scripts
  Makefile
  hack/certmanager.sh
  hack/lib/__sources__.bash
  hack/lib/certmanager.bash
  hack/lib/certmanager_resources/subscription.yaml
Labels: approved, lgtm

#2092 Check if machineconfigpool is available before scaling
  hack/lib/scaleup.bash
Labels: approved, lgtm

#2093 Set min kube version to 1.23.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2094 [release-1.29] Set minKubeVersion to 1.23.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2095 Use TP cert-manager
  hack/lib/certmanager.bash
  hack/lib/certmanager_resources/subscription.yaml
Labels: approved

#2096 Define USER_MANAGEMENT_ALLOWED flag
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/lib.bash
Labels: approved, lgtm

#2097 Append kubeconfigs only if they exist
  test/lib.bash
Labels: approved, lgtm

#2098 :lady_beetle: Cluster-local ksvc displays the URL in text field instead of a link
  test/ui/cypress/code/knative/serving/showcase.js
  test/ui/cypress/e2e/serving/cluster-local.cy.js
Labels: approved, lgtm, kind/bug

#2087 Bump serving components to 1.9
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.9/0-kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.9/0-networkpolicy-mesh.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.9/1-net-istio.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.9/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.9/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.9/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.9/4-serving-post-install-jobs.yaml
  openshift-knative-operator/hack/update-manifests.sh
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#2101 Bump golang deps and run `hack/update-deps.sh --upgrade`
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing-kafka-broker/test/rekt/resources/configmap/broker/broker_config.go
  vendor/knative.dev/eventing-kafka-broker/test/rekt/resources/configmap/broker/broker_config.yaml
  vendor/knative.dev/eventing-kafka-broker/test/rekt/resources/kafkachannel/kafkachannel.go
  vendor/knative.dev/eventing-kafka-broker/test/rekt/resources/kafkachannel/kafkachannel.yaml
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-internal-encryption-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/upgrade/autoscaler.go
  vendor/knative.dev/serving/test/upgrade/probe.go
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm

#2065 Convert extensione2e/kafka tests to REKT
  Makefile
  go.mod
  hack/lib/serverless.bash
  hack/lib/vars.bash
  test/e2e-tests.sh
  test/e2e/knative_eventing_test.go
  test/e2e/knative_serving_test.go
  test/e2ekafka/knative_kafka_test.go
  test/extensione2e/kafka/kafka_channel_ksvc_test.go
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/extensione2e/kafka/source_broker_ksvc.go
  test/extensione2e/kafka/source_channel_ksvc.go
  test/extensione2e/kafka/source_kafka_broker_ksvc_test.go
  test/extensione2e/kafka/source_native_kafka_broker_ksvc_test.go
  test/extensione2e/kafka/user_permissions_test.go
  test/extensione2e/kafka/utils.go
  test/extensione2erekt/containersource_kafkachannel_ksvc_test.go
  test/extensione2erekt/kafkasource_ksvc_test.go
  test/extensione2erekt/main_test.go
  test/extensione2erekt/source_kafkabroker_ksvc_test.go
  test/images-rekt.yaml
  test/lib.bash
  test/monitoringe2e/helpers.go
  test/monitoringe2e/monitoring_test.go
  test/testsuites.yaml
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_binding_test_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source_test_helper.go
  vendor/knative.dev/eventing-kafka/test/lib/creation.go
  vendor/knative.dev/eventing-kafka/test/lib/deletion.go
  vendor/knative.dev/eventing-kafka/test/lib/listers.go
  vendor/knative.dev/eventing-kafka/test/lib/resources/kafka.go
  vendor/modules.txt
Labels: approved, lgtm

#2102 Add `KUBERNETES_MIN_VERSION` to metadata-webhook
  serving/metadata-webhook/config/webhook.yaml
Labels: approved, lgtm

#2069 SRVKE-1446: Add eventing-istio-controller for channel-based mTLS
  hack/generate/csv.sh
  hack/lib/serverless.bash
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.9/1-eventing-istio-controller.yaml
  openshift-knative-operator/hack/update-manifests.sh
  openshift-knative-operator/pkg/eventing/extension.go
  openshift-knative-operator/pkg/eventing/extension_test.go
  openshift-knative-operator/pkg/monitoring/monitoring_eventing.go
  openshift/ci-operator/source-image/Dockerfile
  pkg/istio/eventingistio/istio.go
  test/extensione2erekt/containersource_kafkachannel_ksvc_test.go
  test/extensione2erekt/source_kafkabroker_ksvc_test.go
Labels: approved, lgtm, jira/valid-reference

#2100 Drop `x509ignoreCN=0`
  test/lib.bash
Labels: approved, lgtm
