Repository openshift-knative/serverless-operator, pull requests merged in 2023-07, with the labels that each got.

#2134 Move creating namespaces after generating cert
  hack/lib/mesh.bash
Labels: approved, lgtm

#2137 Use common version to go mod tidy
  hack/update-deps.sh
Labels: approved, lgtm

#2139 Move installation of metadata-webhook back to serverless.bash
  hack/lib/serverless.bash
  test/upstream-e2e-tests.sh
Labels: approved, lgtm

#2142 Use SMCP v2.4 in Service Mesh related tests
  test/servicemesh.go
Labels: approved, lgtm

#2146 Fix promotion tag name in generate CI
  .github/workflows/release-generate-ci.yaml
Labels: approved

#2149 :bug: Fix https://github.com/openshift/console/pull/12935
  test/ui/cypress/code/knative/serving/showcase.js
Labels: approved, lgtm, kind/bug

#2152 [SRVKS-1072] Enable internal-encryption for CI
  hack/lib/serverless.bash
  test/v1beta1/resources/operator.knative.dev_v1beta1_knativeserving_cr.yaml
Labels: approved, lgtm

#2151 Add dependabot and its update deps
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm

#2164 Drop auto bump for the push event
  .github/workflows/validate.yaml
Labels: approved, lgtm

#2130 update metadata for 1.29.1 release
  hack/lib/mesh_resources/smcp.yaml
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  test/servicemesh.go
Labels: approved, lgtm

#2169 Do not add `CURRENT_VERSION_IMAGES` on dependabot's push
  .github/workflows/validate.yaml
Labels: approved, lgtm

#2174 Disable internal encryption for Serverless 1.29 and older
  hack/lib/serverless.bash
Labels: approved, lgtm

#2175 Bump Serving components to release-v1.10
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.10/1-net-istio-netpolicies-mesh.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.10/1-net-kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.10/2-net-istio-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.10/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.10/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.10/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.10/4-serving-post-install-jobs.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#2154 add python image for kn-plugin-func
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2170 Bump creyD/prettier_action from 3.3 to 4.3
  .github/workflows/validate.yaml
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
  templates/serverless-application-quickstart.yaml
Labels: approved, lgtm

#2177 Bump operator to version 1.10
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2182 Disable internal-encryption in upgrade tests due to SRVKS-1107
  hack/lib/serverless.bash
Labels: approved, lgtm, do-not-merge/hold

#2179 Use multiarch test images in upgrade tests
  test/lib.bash
Labels: approved, lgtm

#2189 Pin to OCP dependencies
  go.mod
  go.sum
  hack/update-deps.sh
  knative-operator/pkg/common/util.go
  knative-operator/pkg/controller/knativeeventing/knativeeventing_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativeserving/consoleclidownload/consoleclidownload.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/quickstart/quickstart_test.go
  knative-operator/pkg/monitoring/dashboards/health/healthdashboard_controller.go
  knative-operator/pkg/monitoring/sources/source_deployment_discovery_controller.go
  knative-operator/pkg/webhook/knativeeventing/webhook_mutating.go
  knative-operator/pkg/webhook/knativeeventing/webhook_validating.go
  knative-operator/pkg/webhook/knativekafka/webhook_validating.go
  knative-operator/pkg/webhook/knativeserving/webhook_mutating.go
  knative-operator/pkg/webhook/knativeserving/webhook_validating.go
  openshift-knative-operator/cmd/operator/main.go
  openshift-knative-operator/pkg/common/min_version.go
  serving/ingress/pkg/reconciler/ingress/controller.go
  serving/metadata-webhook/cmd/webhook/main.go
  serving/metadata-webhook/pkg/defaults/config_defaults.go
  serving/metadata-webhook/pkg/defaults/domainmapping_defaults.go
  serving/metadata-webhook/pkg/defaults/ksvc_defaults.go
  serving/metadata-webhook/pkg/defaults/route_defaults.go
  test/servinge2e/deploy_kn_k8s_svc_in_same_namespace_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1alpha1/0000_10_consoleplugin.crd.yaml
  vendor/github.com/openshift/api/console/v1alpha1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#2191 Strimzi operator 0.36.0 and kafka 3.5.0
  hack/lib/strimzi.bash
  hack/lib/vars.bash
Labels: approved, lgtm

#2195 Introduce default environment for eventinge2erekt tests
  test/eventinge2erekt/channelbasedbroker_ksvc_test.go
  test/eventinge2erekt/containersource_channel_ksvc_test.go
  test/eventinge2erekt/main_test.go
  test/eventinge2erekt/pingsource_ksvc_test.go
Labels: approved, lgtm

#2196 Make Serving service mesh tests more stable
  Makefile
  hack/lib/mesh.bash
  hack/lib/mesh_resources/gateway.yaml
  hack/lib/mesh_resources/namespace.yaml
  hack/lib/mesh_resources/smcp.yaml
  hack/lib/mesh_resources/smmr.yaml
  serving/metadata-webhook/config/100-namespace.yaml
  serving/metadata-webhook/pkg/defaults/ksvc_defaults.go
  serving/metadata-webhook/pkg/defaults/ksvc_defaults_test.go
  test/serving.bash
Labels: approved, lgtm

#2197 Increase rekt tests timeouts
  test/extensione2erekt/main_test.go
Labels: approved, lgtm
