Repository openshift-knative/serverless-operator, pull requests merged in 2023-04, with the labels that each got.

#2029 Use golang 1.19 just in docker builds
  .github/workflows/validate.yaml
  go.mod
  hack/update-deps.sh
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/build-image/Dockerfile
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm

#2030 Create a writable temp directory for the go_run() function
  openshift/ci-operator/build-image/Dockerfile
  templates/build-image.Dockerfile
Labels: approved, lgtm

#2031 Make directory creation more robust
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/source-image/Dockerfile
  templates/build-image.Dockerfile
  templates/test-source-image.Dockerfile
Labels: approved

#2032 Partially revert dce94da
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: approved

#2028 Use specific serving_cr and eventing_cr only if exists
  hack/lib/serverless.bash
Labels: approved, lgtm

#2033 Bump build image to Golang 1.19
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/build-image/Dockerfile
  templates/build-image.Dockerfile
Labels: approved, lgtm

#2026 Provide Kafka image through template
  hack/lib/vars.bash
  test/extensione2e/kafka/kafka_source_to_ksvc_test.go
  test/images.go
Labels: approved, lgtm

#2036 Add eventing-istio to test image
  hack/generate/dockerfile.sh
  hack/lib/vars.bash
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
  templates/test-source-image.Dockerfile
Labels: approved, lgtm

#2039 :lady_beetle: [UI] Delete application fix for ODC 4.10
  test/ui/cypress/code/openshift/openshiftConsole.js
Labels: approved, lgtm, area/qe, kind/bug

#2034 Index image includes current bundle and two versions back
  hack/generate/dockerfile.sh
  hack/generate/index.sh
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/project.yaml
  templates/index.Dockerfile
Labels: approved, lgtm

#2037 Run eventing-istio tests in the mesh test job
  Makefile
  hack/lib/vars.bash
  test/eventing-kafka.bash
  test/eventing.bash
Labels: approved, lgtm

#2040 Fix skipping test run when testselect chooses no tests
  test/eventing-kafka.bash
  test/eventing.bash
  test/lib.bash
  test/serving.bash
  test/testsuites.yaml
Labels: approved, lgtm

#2044 Change the source for serverless 1.28 in kitchensink upgrade tests
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2042 Minimal ServiceEntry for Kafka cluster
  hack/lib/mesh_resources/kafka-service-entry.yaml
Labels: approved, lgtm

#2048 Update test-source-image to use new serving tagging schema
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
  templates/test-source-image.Dockerfile
Labels: approved

#2046 Use new image tagging schema for serving
  hack/generate/csv.sh
  hack/lib/catalogsource.bash
  hack/lib/vars.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.8/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.8/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.8/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.8/4-serving-post-install-jobs.yaml
  openshift-knative-operator/hack/update-manifests.sh
  test/lib.bash
  test/serving.bash
Labels: approved, lgtm

#2047 :safety_vest: Add DCO and CONTRIBUTING.md
  CONTRIBUTING.md
  DCO
Labels: documentation, approved, lgtm

#2052 Wait for Serving config propagation
  test/serving.bash
Labels: approved, lgtm

#2054 Run testselect only if CLONEREFS_OPTIONS exist
  hack/lib/testselect.bash
Labels: approved, lgtm

#2056 [knative-client] Update client to 1.8 release
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.8/0-kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.8/1-net-istio.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.8/2-serving-core.yaml
Labels: approved, lgtm
