Repository openshift-knative/serverless-operator, pull requests merged in 2023-10, with the labels that each got.

#2289 SRVKE-1510: Support collecting PingSource metrics in mesh mode
  knative-operator/cmd/manager/main.go
  knative-operator/pkg/monitoring/monitoring.go
  knative-operator/pkg/monitoring/sources/source_deployment_discovery_controller.go
  openshift-knative-operator/pkg/monitoring/helpers.go
  openshift-knative-operator/pkg/monitoring/monitoring_eventing.go
Labels: approved, lgtm, jira/valid-reference

#2272 Create SOP for knative_up != 1
  docs/sops/README.md
  docs/sops/serverless-controller-knative-up.md
Labels: approved, lgtm

#2288 Disable tracing test if no Jaeger present
  test/servinge2e/tracing_test.go
Labels: approved, lgtm

#2291 Bump golang deps to latest commits
  go.mod
  go.sum
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.10/1-eventing-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.10/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.10/4-mt-channel-broker.yaml
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
  vendor/knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/base/reconciler.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.yaml
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/source/source.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/knative.dev/operator/pkg/reconciler/common/ha.go
  vendor/knative.dev/operator/pkg/reconciler/common/hpa.go
  vendor/knative.dev/operator/pkg/reconciler/common/transformers.go
  vendor/knative.dev/operator/pkg/reconciler/common/workload_override.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/istio_quit.go
  vendor/modules.txt
Labels: approved, lgtm

#2295 Update client to v1.10.0
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2276 Tests for cross-tenant communication with Service Mesh
  go.mod
  test/eventinge2erekt/features/encryption.go
  test/eventinge2erekt/servicemesh/main_test.go
  test/eventinge2erekt/servicemesh/multitenant_test.go
  test/extensione2erekt/features/encryption.go
  test/extensione2erekt/servicemesh/main_test.go
  test/extensione2erekt/servicemesh/multitenant_test.go
  test/lib.bash
  vendor/modules.txt
Labels: approved, lgtm

#2300 Trying to fix the bump automation for istio authz chart bump
  .github/workflows/bump.yaml
Labels: approved

#2301 Pass QE robot token when checking out helm chart in bump automation
  .github/workflows/bump.yaml
Labels: approved

#2303 Commit changes for helm chart bump
  .github/workflows/bump.yaml
Labels: approved, lgtm

#2304 Config Git user to be able to commit
  .github/workflows/bump.yaml
Labels: approved, lgtm

#2308 Get helm chart from Github instead of OCI
  .github/workflows/bump.yaml
  hack/generate/mesh-auth-policies.sh
Labels: approved, lgtm

#2309 Bump operator to version 1.11
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeeventing_crd.yaml
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2311 Bump Serving to version 1.11 and add DomainMapping downgrades
  hack/generate/csv.sh
  hack/lib/catalogsource.bash
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.11/istio/1-net-istio-netpolicies-mesh.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.11/istio/2-net-istio-core.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.11/kourier/1-net-kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.11/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.11/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.11/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.11/4-serving-post-install-jobs.yaml
  openshift-knative-operator/pkg/monitoring/monitoring_serving.go
  openshift-knative-operator/pkg/monitoring/monitoring_serving_test.go
  openshift-knative-operator/pkg/monitoring/testdata/rbac.yaml
  openshift/ci-operator/source-image/Dockerfile
  test/e2e/knative_serving_test.go
  test/monitoringe2e/helpers.go
  test/upgrade/installation/serverless.go
Labels: approved, lgtm

#2319 Avoid running channel test in parallel for InMemory and Kafka
  test/upgrade/upgrade_test.go
Labels: approved, lgtm

#2321 Use status codes from http package
  test/eventinge2erekt/features/encryption.go
  test/eventinge2erekt/pingsource_ksvc_test.go
Labels: approved, lgtm

#2322 Partially cherry-pick https://github.com/openshift-knative/serverless-operator/pull/2308
  hack/generate/mesh-auth-policies.sh
Labels: approved, lgtm

#2323 [release-1.31] manually fix the CSV image version
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2324 Create update generated files PR on push that are not for dependabot
  .github/workflows/validate.yaml
Labels: approved, lgtm

#2314 separate execution of kitchensink e2e tests so they don't timeout on 2h CI step limits
  Makefile
  test/kitchensink-e2e-tests.sh
Labels: approved, lgtm

#2328 Drop the version in storage-version-migration containers
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.11/istio/1-net-istio-netpolicies-mesh.yaml
Labels: approved, lgtm

#2336 Fix checking if Jaeger is installed
  test/servinge2e/tracing_test.go
Labels: approved, lgtm

#2325 Start upgrade sequence with 1.30.1
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2332 Remove workaround for SRVKE-1506
  test/upgrade/kitchensink/kitchensink.go
Labels: approved, lgtm

#2330 Bump OCP min version to 4.11
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2310 Bump eventing components v1.11
  knative-operator/deploy/resources/knativekafka/broker/eventing-kafka-broker.yaml
  knative-operator/deploy/resources/knativekafka/channel/eventing-kafka-channel.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-tls-networking.yaml
  knative-operator/deploy/resources/knativekafka/sink/eventing-kafka-sink.yaml
  knative-operator/deploy/resources/knativekafka/source/eventing-kafka-source.yaml
  knative-operator/hack/update-manifests.sh
  knative-operator/pkg/controller/knativekafka/eventing_tls.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller.go
  knative-operator/pkg/controller/knativekafka/knativekafka_controller_test.go
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/1-eventing-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/1-eventing-istio-controller.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/2-eventing-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/3-in-memory-channel.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/4-mt-channel-broker.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/5-eventing-post-install.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/6-eventing-tls-networking.yaml
  openshift-knative-operator/hack/update-manifests.sh
  openshift/ci-operator/source-image/Dockerfile
  templates/csv.yaml
  test/eventing-kafka.bash
  test/images-rekt.yaml
Labels: approved, lgtm

#2342 Add issue template for release
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, lgtm

#2352 [release-1.31] Add new kube-rbac-proxy with http2-disable option
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
Labels: approved, lgtm

#2351 [release-1.30] Add new kube-rbac-proxy with http2-disable option
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
Labels: approved, lgtm

#2363 Improve eventing istio resources lifecycle
  openshift-knative-operator/pkg/eventing/extension.go
  openshift-knative-operator/pkg/eventing/extension_test.go
  test/monitoringe2e/monitoring_test.go
Labels: approved, lgtm
