Repository openshift-knative/serverless-operator, pull requests merged in 2024-09, with the labels that each got.

#2825 no-tracing variant for test-e2e-with-kafka
  Makefile
Labels: approved, lgtm

#2831 Only parse `transport-encryption` feature flag in KnativeKafka
  knative-operator/pkg/controller/knativekafka/eventing_tls.go
Labels: approved, lgtm

#2832 Update Release checklist to recreate Konflux SA token
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, lgtm

#2833 :bug: Prevent slash from appearing in random IDs
  hack/lib/vars.bash
  test/lib.bash
Labels: approved, lgtm, kind/bug

#2834 Fix: call hack/generate by full path
  Makefile
Labels: approved

#2835 Replace FROM in Dockerfiles with real images
  hack/lib/catalogsource.bash
  knative-operator/Dockerfile
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
Labels: approved, lgtm

#2838 Fix Dockerfiles and patches
  knative-operator/Dockerfile
  knative-operator/dockerfile.patch
  openshift-knative-operator/Dockerfile
  openshift-knative-operator/dockerfile.patch
  serving/ingress/Dockerfile
Labels: approved, lgtm

#2839 Re-generate Dockerfiles and fix patches
  knative-operator/Dockerfile
  knative-operator/dockerfile.patch
  openshift-knative-operator/Dockerfile
  openshift-knative-operator/dockerfile.patch
  serving/ingress/Dockerfile
Labels: approved, lgtm

#2837 [SRVKS-1264] Remove deprecated TLS secret
  openshift-knative-operator/pkg/serving/extension.go
  test/servinge2e/deprecated_resources_test.go
Labels: approved, lgtm

#2841 Fix TLS feature flag parsing for KnativeKafka
  knative-operator/pkg/controller/knativekafka/eventing_tls.go
Labels: approved, lgtm

#2843 Update client midstream to 1.14
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2848 Set min OCP to 4.13
  hack/lib/certmanager.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/project.yaml
  test/upgrade/installation/openshift.go
Labels: approved, lgtm

#2824 [main] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-pull-request.yaml
  .tekton/serverless-index-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: approved, do-not-merge/hold

#2866 Bump Serving manifests to 1.15
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/istio/1-net-istio-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/kourier/1-net-kourier.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/1-serving-crds.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/2-serving-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/3-serving-hpa.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/4-serving-post-install-jobs.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm

#2869 Bump Operator to 1.15
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2870 Force builder images to Golang 1.22
  Makefile
  knative-operator/Dockerfile
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
Labels: approved, lgtm

#2868 [main] Add Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-pull-request.yaml
  .tekton/serverless-index-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: approved, lgtm

#2871 Tweak install of generate in Makefile & minor gh action fixes
  .github/workflows/dependabot-deps.yaml
  .github/workflows/validate.yaml
  Makefile
Labels: approved, lgtm

#2872 Empty GOFLAGS when running go install
  Makefile
Labels: approved, lgtm, do-not-merge/hold

#2879 Fix source path for upstream tests
  hack/lib/vars.bash
Labels: approved, lgtm

#2883 [release-1.34] Configure ingress certificate for downstream testing
  knative-operator/Dockerfile
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
  test/lib.bash
Labels: approved, lgtm

#2886 Bump to latest upstream operator 1.15.5
  go.mod
  go.sum
  vendor/knative.dev/operator/pkg/reconciler/common/ha.go
  vendor/knative.dev/operator/pkg/reconciler/common/hpa.go
  vendor/knative.dev/operator/pkg/reconciler/common/workload_override.go
  vendor/modules.txt
Labels: approved, lgtm

#2890 [release-1.34] Bump to latest upstream operator 1.14.9
  go.mod
  go.sum
  hack/patches/022-keep-kafka-channel-replica-override.patch
  vendor/knative.dev/operator/pkg/reconciler/common/ha.go
  vendor/knative.dev/operator/pkg/reconciler/common/hpa.go
  vendor/knative.dev/operator/pkg/reconciler/common/workload_override.go
  vendor/modules.txt
Labels: approved, lgtm

#2888 Bump linter version
  .github/workflows/validate.yaml
  .golangci.yaml
  test/installplan.go
Labels: approved, lgtm

#2891 use SCALE_UP=6 for soak test
  Makefile
Labels: approved, lgtm

#2889 Update client images to release-v1.15
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved

#2895 Install Skopeo to get latest Konflux SHAs
  templates/build-image.Dockerfile
Labels: approved, lgtm

#2887 Use istio.sidecar.inject label instead of annotation
  docs/full-mesh.md
  docs/service-mesh/eventing/README.md
  docs/service-mesh/eventing/resources/kafka-broker-example.yaml
  docs/service-mesh/eventing/resources/ping-source-kservice.yaml
  docs/service-mesh/eventing/resources/ping-source.yaml
  docs/service-mesh/serving/mesh.md
  hack/lib/serverless.bash
  hack/lib/tracing.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  serving/metadata-webhook/README.md
  serving/metadata-webhook/pkg/defaults/config_defaults.go
  serving/metadata-webhook/pkg/defaults/config_defaults_test.go
  serving/metadata-webhook/pkg/defaults/ksvc_defaults.go
  serving/metadata-webhook/pkg/defaults/ksvc_defaults_test.go
  templates/csv.yaml
  test/extensione2e/kafka/utils.go
  test/servinge2e/kourier/servicemesh_test.go
Labels: approved, lgtm

#2899 [main] Fix links in CSV
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#2898 [release-1.34] Fix links in CSV
  hack/generate/csv.sh
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm
