Repository openshift-knative/serverless-operator, pull requests merged in 2024-11, with the labels that each got.

#2986 Wait for imageStreamTag to be imported before build
  hack/lib/catalogsource.bash
Labels: approved

#2994 [main] Add Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-413-pull-request.yaml
  .tekton/serverless-index-135-fbc-413-push.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: approved, lgtm

#2992 [SRVCOM-3372] Allow to override labels in knative-serving-ingress ns
  docs/gitops/README.md
  docs/gitops/serverless/300-serving.yaml
  hack/patches/022-serving-ingress-ns-filter.patch
  knative-operator/Dockerfile
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
  serving/metadata-webhook/Dockerfile
  templates/csv.yaml
  test/e2e/dashboards.go
  test/e2e/knative_serving_test.go
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm

#2997 SRVCOM-3398 must-gather collects logs for all namespaces with Knative resources
  must-gather/bin/gather_knative
Labels: approved

#3005 [main] Add Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-413-pull-request.yaml
  .tekton/serverless-index-135-fbc-413-push.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: do-not-merge/hold

#3001 Bump OCP versions to minVersion: 4.14, maxVersion 4.18
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
  templates/csv.yaml
Labels: approved

#3013 [RELEASE-1.34][SRVKS-1287] Allow to override the ha proxy default route timeout 1.34
  knative-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/Dockerfile
  serving/ingress/Dockerfile
  serving/ingress/pkg/reconciler/ingress/resources/route.go
  serving/ingress/pkg/reconciler/ingress/resources/route_test.go
  templates/csv.yaml
Labels: approved, lgtm

#3018 Update must-gather Dockerfile and script to use env for logs dir
  must-gather/Dockerfile
  must-gather/bin/gather
Labels: approved

#3015 Bump 1.33.3
  hack/lib/testselect.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#3022 Specify the expected version of resources in downgrade error message
  test/upgrade/installation/serverless.go
Labels: approved, lgtm

#3017 [main][SRVKS-1286] Override activator termination grace perio…
  openshift-knative-operator/pkg/monitoring/rbac_proxy_injection.go
  openshift-knative-operator/pkg/serving/extension.go
Labels: approved, lgtm

#3023 [SRVKS-1288] Fix Kourier ns cleanup
  hack/patches/022-serving-ingress-ns-filter.patch
  must-gather/Dockerfile
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator-index/v4.18/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  openshift-knative-operator/pkg/serving/extension.go
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm

#3026 Set base image ubi-minimal and user for bundle image
  olm-catalog/serverless-operator/Dockerfile
  templates/main.Dockerfile
Labels: approved, lgtm

#3019 [main] Add Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-index-135-fbc-418-pull-request.yaml
  .tekton/serverless-index-135-fbc-418-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: approved, lgtm

#3032 Regen Dockerfile patches
  knative-operator/Dockerfile
  knative-operator/dockerfile.patch
  must-gather/Dockerfile
  openshift-knative-operator/Dockerfile
  openshift-knative-operator/dockerfile.patch
  serving/ingress/Dockerfile
  serving/metadata-webhook/Dockerfile
Labels: approved, lgtm

#3027 Use ImageContentSourcePolicy only with enforced Index from Konflux
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#3033 Use required labels in bundle image
  olm-catalog/serverless-operator/Dockerfile
  templates/main.Dockerfile
Labels: approved, lgtm

#3030 lower timeout for soak tests
  test/lib.bash
Labels: approved, lgtm

#3044 [main] Add Konflux configurations
  .tekton/fbc-builder.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-418-pull-request.yaml
Labels: approved, lgtm

#3035 lower CPU requests for dispatchers in kitchensink test
  test/lib.bash
Labels: approved, do-not-merge/hold

#3042 Use knative-main as tag for webhook
  serving/metadata-webhook/config/webhook.yaml
Labels: approved, lgtm

#3038 Test long running requests in Serving
  hack/lib/vars.bash
  serving/ingress/pkg/reconciler/ingress/resources/route.go
  serving/ingress/pkg/reconciler/ingress/resources/route_test.go
  test/images.go
  test/lib.bash
  test/servinge2e/servicemesh/longrunning/timeout_test.go
Labels: approved, lgtm

#3050 Add license to bundle image
  olm-catalog/serverless-operator/Dockerfile
  templates/main.Dockerfile
Labels: approved

#3057 Install yq v3 in bump workflow
  .github/workflows/bump.yaml
Labels: approved, lgtm

#3056 Fix SO index
  olm-catalog/serverless-operator-index/Dockerfile
  templates/index.Dockerfile
Labels: approved, lgtm

#3058 [main] Add Konflux configurations
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-index-136-fbc-414-pull-request.yaml
  .tekton/serverless-index-136-fbc-414-push.yaml
  .tekton/serverless-index-136-fbc-415-pull-request.yaml
  .tekton/serverless-index-136-fbc-415-push.yaml
  .tekton/serverless-index-136-fbc-416-pull-request.yaml
  .tekton/serverless-index-136-fbc-416-push.yaml
  .tekton/serverless-index-136-fbc-417-pull-request.yaml
  .tekton/serverless-index-136-fbc-417-push.yaml
  .tekton/serverless-index-136-fbc-418-pull-request.yaml
  .tekton/serverless-index-136-fbc-418-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: approved, lgtm

#3054 Separate installing cert manager operator and certificates
  hack/lib/certmanager.bash
Labels: approved, lgtm

#3059 [release-1.35] Add Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-index-135-fbc-418-pull-request.yaml
  .tekton/serverless-index-135-fbc-418-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: approved

#3045 Add script to generate override snapshot
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
  Makefile
  hack/generate/override-snapshot.sh
  hack/verify-diff.sh
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved
