Repository openshift-knative/serverless-operator, pull requests merged in 2024-12, with the labels that each got.

#3072 Add script to add override snapshots
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
  Makefile
  hack/generate/override-snapshot.sh
  hack/verify-diff.sh
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#3079 [release-1.35] Use Konflux image in yaml for metadata-webhook
  Makefile
  hack/generate/metadata-webhook.sh
  serving/metadata-webhook/config/webhook.yaml
Labels: approved, lgtm

#3064 Add skopeo OS, arch overrides
  hack/lib/images.bash
Labels: approved, lgtm

#2985 Default to minAvailable: 1 in Servings PodDisruptionBudgets
  openshift-knative-operator/pkg/serving/extension.go
  openshift-knative-operator/pkg/serving/extension_test.go
  openshift-knative-operator/pkg/serving/poddisruptionbudget.go
  openshift-knative-operator/pkg/serving/poddisruptionbudget_test.go
Labels: approved, lgtm

#3120 [release-1.34] Separate installing cert manager operator and certificates
  hack/lib/certmanager.bash
  knative-operator/Dockerfile
  knative-operator/dockerfile.patch
  openshift-knative-operator/Dockerfile
  openshift-knative-operator/dockerfile.patch
  serving/ingress/Dockerfile
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
Labels: approved, lgtm

#3133 [release-1.35] Regenerate CSV
  Makefile
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  test/images-rekt.yaml
Labels: approved, lgtm

#3134 [release-1.35] Regenerate CSV
  Makefile
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#3146 [release-1.35] Fix update-pipelines tag index
  hack/generate/update-pipelines.sh
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  test/images-rekt.yaml
Labels: approved, lgtm

#3055 Drop kourier <> OSSM integration test as it is no longer supported
  test/servinge2e/kourier/custom_route_test.go
  test/servinge2e/kourier/service_to_service_test.go
  test/servinge2e/kourier/servicemesh_test.go
Labels: approved, lgtm, ok-to-test

#3151 Link to Build Status Dashboard in release issue template
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, lgtm

#3152 [release-1.35] Update CSV to latest builds
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#3153 Move override-snapshot generation into separate Makefile target
  .github/workflows/validate.yaml
  Makefile
Labels: approved, lgtm

#3158 Increase scaling worker nodes to 6 for upgrade tests
  Makefile
Labels: approved, lgtm

#3157 raise tempo memory limits
  hack/lib/tracing.bash
Labels: approved, lgtm

#3103 [SRVKS-1298] Don't copy ingress Argo metadata to auto-generated OCP routes
  docs/gitops/README.md
  docs/gitops/serverless/100-subscription.yaml
  docs/gitops/serverless/400-ksvc.yaml
  hack/dev.sh
  serving/ingress/pkg/reconciler/ingress/resources/route.go
  serving/ingress/pkg/reconciler/ingress/resources/route_test.go
Labels: approved, lgtm

#3080 [main] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-index-136-fbc-414-pull-request.yaml
  .tekton/serverless-index-136-fbc-414-push.yaml
  .tekton/serverless-index-136-fbc-415-pull-request.yaml
  .tekton/serverless-index-136-fbc-415-push.yaml
  .tekton/serverless-index-136-fbc-416-pull-request.yaml
  .tekton/serverless-index-136-fbc-416-push.yaml
  .tekton/serverless-index-136-fbc-417-pull-request.yaml
  .tekton/serverless-index-136-fbc-417-push.yaml
  .tekton/serverless-index-136-fbc-418-pull-request.yaml
  .tekton/serverless-index-136-fbc-418-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: approved, lgtm

#3161 Add renovate config
  renovate.json
Labels: approved

#3182 [release-1.35] Fix override-snapshot generation
  .github/workflows/validate.yaml
  Makefile
  hack/verify-diff.sh
Labels: approved

#3200 [release-1.35] Update golang.org/x/crypto to 0.31.0
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved

#3185 Copy logs to SHARED_DIR on exit
  hack/lib/ui.bash
Labels: approved, lgtm
