Repository openshift-knative/serverless-operator, pull requests merged in 2024-03, with the labels that each got.

#2531 Remove version check in KnativeServing
  hack/patches/017-knativeserving-remove-version-check.patch
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm

#2534 Update build image to use new k8s pkg repo
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#2508 Use the operator-registry image more consistently
  olm-catalog/serverless-operator/index/Dockerfile
  templates/index.Dockerfile
Labels: approved, lgtm

#2545 [RELEASE-1.32] Use the operator-registry image more consistently
  olm-catalog/serverless-operator/index/Dockerfile
  openshift-knative-operator/cmd/operator/kodata/knative-eventing/1.11/2-eventing-core.yaml
  templates/index.Dockerfile
Labels: approved, lgtm

#2540 [SRVCOM-2986][release-1.32] Add new annotation format required for operators
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/csv.yaml
Labels: approved, lgtm

#2542 [RELEASE-1.32] Add required label for trusted-ca ConfigMap
  knative-operator/pkg/controller/knativeserving/knativeserving_controller.go
  knative-operator/pkg/controller/knativeserving/knativeserving_controller_test.go
Labels: approved, lgtm

#2528 Install Serverless using release-next artifacts
  Makefile
  hack/generate/csv.sh
  hack/lib/images.bash
  hack/lib/serverless.bash
  hack/lib/vars.bash
  knative-operator/hack/update-manifests.sh
  openshift-knative-operator/hack/update-manifests.sh
Labels: approved, lgtm

#2550 [release-1.32] Bump ce 2.15.2 ocp
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/like_expression.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/logic_expressions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/.protocol.go.swp
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/modules.txt
Labels: approved, lgtm

#2551 [main] Bump the rest of the CE library to 2.15.2 as well
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/like_expression.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/logic_expressions.go
  vendor/modules.txt
Labels: approved, lgtm

#2554 [release-1.32] Add bash script to downgrade kafka contracts and run as part of downgrade tests
  test/upgrade/installation/downgrade.sh
  test/upgrade/installation/serverless.go
Labels: approved, lgtm

#2556 Add `.idea/` folder to `.gitignore`
  .gitignore
Labels: approved, lgtm

#2555 [release-1.32] Update contract downgrade script to be standalone
  test/upgrade/installation/downgrade.sh
  test/upgrade/installation/serverless.go
Labels: approved, lgtm

#2558 :broom: Use own yq installation
  .github/workflows/bump.yaml
  .github/workflows/dependabot-deps.yaml
  .github/workflows/release-generate-ci.yaml
  .github/workflows/validate.yaml
  README.md
  hack/lib/metadata.bash
Labels: approved, lgtm

#2563 [UI] :gift: Support for ODC 4.15
  test/ui-e2e-tests.sh
  test/ui/cypress/code/knative/serving/showcase.js
  test/ui/cypress/code/openshift/openshiftConsole.js
  test/ui/cypress/e2e/eventing/types.cy.js
  test/ui/cypress/e2e/serving/cluster-local.cy.js
  test/ui/cypress/e2e/serving/multiple-revisions.cy.js
  test/ui/package-lock.json
  test/ui/package.json
Labels: enhancement, approved, lgtm

#2569 Bump strimzi to 0.40.0 and apache kafka to 3.7.0
  hack/lib/strimzi.bash
  hack/lib/vars.bash
Labels: approved, lgtm

#2524 Bump Serving manifests to 1.12
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.12/istio/1-net-istio-core.yaml
  openshift-knative-operator/cmd/operator/kodata/ingress/1.12/kourier/1-net-kourier.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.12/1-serving-crds.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.12/2-serving-core.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.12/3-serving-hpa.yaml
  openshift-knative-operator/cmd/operator/kodata/knative-serving/1.12/4-serving-post-install-jobs.yaml
  openshift/ci-operator/source-image/Dockerfile
  test/upgrade/installation/serverless.go
  test/v1beta1/resources/operator.knative.dev_v1beta1_knativeserving_cr.yaml
Labels: approved, lgtm

#2572 Bump operator yaml version to 1.13
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2571 Remove deprecated call to oc sa get-token
  test/lib.bash
Labels: approved, lgtm

#2576 Upgrade sequence does not include 1.31.1
  hack/cmd/bumpso/bumpso.go
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2577 SRVCOM-2642 Include must-gather image in CSV relatedImages
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2581 Use promotion by name for operator images
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2584 [release-1.32] Use serverless-openshift-knative-operator for webhook
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved

#2575 [release-1.32] Bump to 1.32.1
  .github/workflows/release-generate-ci.yaml
  .github/workflows/validate.yaml
  hack/lib/__sources__.bash
  hack/lib/catalogsource.bash
  hack/lib/strimzi.bash
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/index/configs/index.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  templates/index.Dockerfile
Labels: approved, lgtm

#2582 Use promotion by name for operator images
  hack/lib/__sources__.bash
  hack/lib/catalogsource.bash
  hack/lib/images.bash
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  templates/index.Dockerfile
Labels: approved, lgtm

#2586 [release-1.32] use current index image by default
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#2583 Generate Index yaml entries for older channels correctly
  hack/generate/index.sh
  templates/index.yaml
Labels: approved, lgtm
