Repository openshift-knative/serverless-operator, pull requests merged in 2024-10, with the labels that each got.

#2892 Drop OSSM 2.x dependencies and cleanup scripts
  hack/lib/mesh_resources/namespace.yaml
  hack/lib/mesh_resources/subscription.yaml
  hack/lib/serverless.bash
  hack/lib/tracing.bash
  hack/lib/vars.bash
  test/servinge2e/tracing_test.go
Labels: approved, lgtm

#2916 Fix Istio default and CSV image
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2914 Include `test/images-rekt.yaml` in pattern check of verify-diff.sh too
  hack/verify-diff.sh
Labels: approved

#2917 Bump backstage-plugins to v1.15
  Makefile
  hack/lib/images.bash
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-backstage-plugins-eventmesh-backend.yaml
Labels: approved, lgtm

#2918 Use Konflux built func-utils image in CSV
  hack/generate/csv.sh
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2915 Set max OCP version to 4.17
  knative-operator/deploy/resources/quickstart/serverless-application-quickstart.yaml
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
  templates/test-source-image.Dockerfile
Labels: approved, lgtm

#2920 Use registry.redhat.io reference in CSV
  hack/lib/catalogsource.bash
  hack/lib/images.bash
  olm-catalog/serverless-operator/index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2921 Remove specific image override for storage version migration
  hack/lib/catalogsource.bash
Labels: approved

#2924 Fix konflux index and bundle cel expressions to avoid build loops
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-pull-request.yaml
  .tekton/serverless-index-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
  Makefile
  hack/lib/catalogsource.bash
  hack/lib/serverless.bash
  hack/verify-diff.sh
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator-index/configs/index.yaml
  templates/index.Dockerfile
  test/lib.bash
Labels: approved, lgtm

#2904 [main] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-pull-request.yaml
  .tekton/serverless-index-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: do-not-merge/hold

#2934 Remove temporary catalog file
  hack/generate/catalog.sh
Labels: approved, lgtm

#2933 Remove multi-arch builds in GH actions
  .github/workflows/multiarch-build.yaml
Labels: approved, lgtm

#2882 Configure ingress certificate for downstream testing
  test/lib.bash
Labels: approved, lgtm

#2936 Support patch releases for Konflux builds
  .github/workflows/release-generate-ci.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-push.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
  Makefile
  hack/generate/update-pipelines.sh
Labels: approved, lgtm

#2938 Check in ImageContentSourcePolicy for nightly installations
  .github/workflows/validate.yaml
  .gitignore
  hack/generate/catalog.sh
  hack/lib/catalogsource.bash
  olm-catalog/serverless-operator-index/image_content_source_policy.yaml
Labels: approved, lgtm

#2908 Update upgrade test image template to use Konflux images
  hack/lib/images.bash
  test/lib.bash
Labels: approved, lgtm

#2950 Support console unmanaged mode
  knative-operator/pkg/controller/knativeserving/consoleutil/util.go
Labels: approved, lgtm

#2955 soak, lower kafka-source-dispatcher CPU requests
  test/lib.bash
Labels: approved, lgtm

#2959 Use production ready service mesh proxy image for Kourier
  hack/generate/catalog.sh
  hack/lib/images.bash
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2961 Parse major and minor version from current OCP
  hack/lib/images.bash
Labels: approved

#2962 Use production ready kube-rbac-proxy from registry.redhat.io
  hack/generate/catalog.sh
  hack/generate/csv.sh
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#2954 Allow forcing konflux index
  hack/lib/catalogsource.bash
Labels: approved

#2969 Do not fail if FORCE_KONFLUX_INDEX is undefined
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#2968 Add rhel suffix to image references
  Makefile
  hack/lib/catalogsource.bash
  hack/lib/images.bash
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator-index/image_content_source_policy.yaml
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2971 Install tools for Mesh tests
  Makefile
Labels: approved, lgtm

#2974 Use INDEX_IMAGE from Konflux for generating ImageContentSourcePolicy
  hack/generate/catalog.sh
Labels: approved, lgtm

#2977 Don't use rhel suffix for bundle image name
  hack/lib/images.bash
Labels: approved, lgtm

#2979 optionally skip certmanager install on "make install"
  hack/install.sh
  hack/lib/vars.bash
Labels: approved, lgtm
