Repository openshift-knative/serverless-operator, pull requests merged in 2025-02, with the labels that each got.

#3371 Resolve quay repo correctly on knative-nightly tag
  hack/lib/images.bash
Labels: approved, lgtm

#3366 Bump Serving manifests to 1.16
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/istio/1-net-istio-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/kourier/1-net-kourier.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/2-eventing-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/1-serving-crds.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/2-serving-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/3-serving-hpa.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/4-serving-post-install-jobs.yaml
  openshift/ci-operator/source-image/Dockerfile
  test/images-rekt.yaml
Labels: approved, lgtm

#2853 Bump to Strimzi 0.43.0 operator and Kafka operand to 3.8
  hack/lib/strimzi.bash
  hack/lib/vars.bash
Labels: approved, lgtm

#3367 [release-1.35] Bump patch version for 1.35 to 1.35.1
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-index-135-fbc-418-push.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
  must-gather/Dockerfile
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator-index/configs/index.yaml
  olm-catalog/serverless-operator/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  test/upgrade/installation/channelv2_downgrade.go
Labels: approved, lgtm

#3330 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#3378 Bump to Strimzi 0.45.0 operator and Kafka operand to 3.9
  hack/lib/strimzi.bash
  hack/lib/vars.bash
Labels: approved, lgtm

#3395 [release-1.35] Run testselect directly
  hack/lib/testselect.bash
Labels: approved, lgtm

#3396 Operator version bump to v1.16
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/hack/002-serving-drop-unsupported-fields.patch
  olm-catalog/serverless-operator/hack/005-drop-namespace-override.patch
  olm-catalog/serverless-operator/hack/update-manifests.sh
  olm-catalog/serverless-operator/manifests/operator_v1beta1_knativeserving_crd.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#3448 [main] Update dependabot configurations
  renovate.json
Labels: needs-ok-to-test

#3373 [release-1.35] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-index-135-fbc-414-pull-request.yaml
  .tekton/serverless-index-135-fbc-414-push.yaml
  .tekton/serverless-index-135-fbc-415-pull-request.yaml
  .tekton/serverless-index-135-fbc-415-push.yaml
  .tekton/serverless-index-135-fbc-416-pull-request.yaml
  .tekton/serverless-index-135-fbc-416-push.yaml
  .tekton/serverless-index-135-fbc-417-pull-request.yaml
  .tekton/serverless-index-135-fbc-417-push.yaml
  .tekton/serverless-index-135-fbc-418-pull-request.yaml
  .tekton/serverless-index-135-fbc-418-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: needs-ok-to-test

#3372 [main] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: needs-ok-to-test

#3447 [RELEASE-1.35] [SRVKS-1307] Fix nil check in Serving reconciler
  hack/patches/022-serving-ingress-ns-filter.patch
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm

#3455 [release-1.35] Update Konflux configurations
  .tekton/fbc-builder.yaml
Labels: approved, lgtm, ok-to-test
