Repository openshift-knative/serverless-operator, pull requests merged in 2025-05, with the labels that each got.

#3641 use floats for "le"
  test/monitoringe2e/helpers.go
Labels: approved, lgtm, ok-to-test

#3609 [main] Update dependabot configurations
  .github/dependabot.yml
  renovate.json
Labels: approved, lgtm

#3660 [main] Update Konflux configurations
  .tekton/serverless-bundle-137-pull-request.yaml
  .tekton/serverless-bundle-137-push.yaml
  .tekton/serverless-index-137-fbc-414-pull-request.yaml
  .tekton/serverless-index-137-fbc-414-push.yaml
  .tekton/serverless-index-137-fbc-415-pull-request.yaml
  .tekton/serverless-index-137-fbc-415-push.yaml
  .tekton/serverless-index-137-fbc-416-pull-request.yaml
  .tekton/serverless-index-137-fbc-416-push.yaml
  .tekton/serverless-index-137-fbc-417-pull-request.yaml
  .tekton/serverless-index-137-fbc-417-push.yaml
  .tekton/serverless-index-137-fbc-418-pull-request.yaml
  .tekton/serverless-index-137-fbc-418-push.yaml
  .tekton/serverless-ingress-137-pull-request.yaml
  .tekton/serverless-ingress-137-push.yaml
  .tekton/serverless-kn-operator-137-pull-request.yaml
  .tekton/serverless-kn-operator-137-push.yaml
  .tekton/serverless-metadata-webhook-137-pull-request.yaml
  .tekton/serverless-metadata-webhook-137-push.yaml
  .tekton/serverless-must-gather-137-pull-request.yaml
  .tekton/serverless-must-gather-137-push.yaml
  .tekton/serverless-openshift-kn-operator-137-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-137-push.yaml
Labels: approved, lgtm, ok-to-test

#3668 Update bundle (run `make generated-files`)
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  test/images-rekt.yaml
Labels: approved, lgtm

#3679 Bump eventing-kafka-broker to 1.17
  knative-operator/deploy/resources/knativekafka/broker/eventing-kafka-broker.yaml
  knative-operator/deploy/resources/knativekafka/channel/eventing-kafka-channel.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  knative-operator/deploy/resources/knativekafka/sink/eventing-kafka-sink.yaml
  knative-operator/deploy/resources/knativekafka/source/eventing-kafka-source.yaml
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm, ok-to-test

#3681 fix: correct input condition for override snapshot
  .github/workflows/validate.yaml
Labels: approved

#3683 Bump eventing integrations to 1.17
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#3686 Bump eventing istio to 1.17
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-eventing-istio-controller.yaml
  openshift/ci-operator/source-image/Dockerfile
Labels: approved, lgtm, size/M

#3687 Bump backstage plugins to 1.17
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-backstage-plugins-eventmesh-backend.yaml
Labels: approved, lgtm, ok-to-test

#3688 Bump client and func to 1.17
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
Labels: approved, lgtm

#3689 Bump serving to 1.17
  hack/lib/images.bash
  hack/lib/vars.bash
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/istio/1-net-istio-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/ingress/latest/kourier/1-net-kourier.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/1-serving-crds.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/2-serving-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/3-serving-hpa.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-serving/latest/4-serving-post-install-jobs.yaml
  openshift/ci-operator/source-image/Dockerfile
  test/images-rekt.yaml
  test/servinge2e/encryption/encryption_test.go
  test/servinge2e/helpers.go
  test/servinge2e/kourier/custom_route_test.go
  test/servinge2e/kourier/service_to_service_test.go
  test/servinge2e/kourier/verify_http_and_https_test.go
  test/servinge2e/kourier/verify_route_conflict_test.go
  test/servinge2e/servicemesh/helpers.go
  test/servinge2e/servicemesh/multitenant_test.go
  test/servinge2e/tracing_test.go
Labels: approved, lgtm

#3694 [release-1.36] Run make generated-files
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
Labels: approved, lgtm

#3698 [release-1.36] Update Konflux configurations
  .tekton/bundle-build.yaml
Labels: approved, lgtm, ok-to-test

#3705 [release-1.36] Run make generated-files
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
Labels: approved, lgtm

#3708 [release-1.36] Run make generated-files
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#3710 [release-1.36] Run make generated-files
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
Labels: approved, lgtm
