Repository openshift-knative/serverless-operator, pull requests merged in 2025-03, with the labels that each got.

#3454 [main] Update Konflux configurations
  .tekton/fbc-builder.yaml
Labels: approved, lgtm, needs-ok-to-test

#3460 [main] Update Konflux configurations
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-index-136-fbc-414-pull-request.yaml
  .tekton/serverless-index-136-fbc-414-push.yaml
  .tekton/serverless-index-136-fbc-415-pull-request.yaml
  .tekton/serverless-index-136-fbc-415-push.yaml
  .tekton/serverless-index-136-fbc-416-pull-request.yaml
  .tekton/serverless-index-136-fbc-416-push.yaml
  .tekton/serverless-index-136-fbc-417-pull-request.yaml
  .tekton/serverless-index-136-fbc-417-push.yaml
  .tekton/serverless-index-136-fbc-418-pull-request.yaml
  .tekton/serverless-index-136-fbc-418-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#3461 Create ImageDigestMirrorSet for fbc-fips-check-oci-ta task
  .tekton/images-mirror-set.yaml
  hack/generate/catalog.sh
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#3506 Add mirrors under correct field in ImageDigestMirrorSet YAML
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#3520 Create the `Run make generated-files` PRs as Serverless-QE robot
  .github/workflows/validate.yaml
Labels: approved, lgtm

#3538 [release-1.35] Update Konflux configurations
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: needs-ok-to-test

#3480 [main] Update Konflux configurations
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-index-136-fbc-414-pull-request.yaml
  .tekton/serverless-index-136-fbc-414-push.yaml
  .tekton/serverless-index-136-fbc-415-pull-request.yaml
  .tekton/serverless-index-136-fbc-415-push.yaml
  .tekton/serverless-index-136-fbc-416-pull-request.yaml
  .tekton/serverless-index-136-fbc-416-push.yaml
  .tekton/serverless-index-136-fbc-417-pull-request.yaml
  .tekton/serverless-index-136-fbc-417-push.yaml
  .tekton/serverless-index-136-fbc-418-pull-request.yaml
  .tekton/serverless-index-136-fbc-418-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: approved, needs-ok-to-test

#3551 [release-1.35] Create ImageDigestMirrorSet for fbc-fips-check-oci-ta task
  .tekton/images-mirror-set.yaml
  hack/generate/catalog.sh
  hack/lib/catalogsource.bash
Labels: approved, lgtm

#3560 [release-1.35][SRVKS-1301] Update knative/operator to fix webhook issues
  go.mod
  go.sum
  hack/patches/020-backstage_plugins_eventmesh_backend.patch
  vendor/knative.dev/operator/pkg/reconciler/common/deployments.go
  vendor/knative.dev/operator/pkg/reconciler/common/install.go
  vendor/knative.dev/operator/pkg/reconciler/common/stages.go
  vendor/knative.dev/operator/pkg/reconciler/knativeeventing/knativeeventing.go
  vendor/knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go
  vendor/knative.dev/operator/pkg/reconciler/manifests/install.go
  vendor/modules.txt
Labels: approved, lgtm

#3569 [release-1.35] Run make generated-files
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
Labels: approved, lgtm

#3570 add Kaustubh-pande as approver and reviewer
  OWNERS_ALIASES
Labels: approved

#3343 Add CSV CVE check
  Makefile
  hack/verify-csv-revisions.sh
  hack/verify-csv.sh
Labels: approved, lgtm
