Repository openshift-knative/serverless-operator, pull requests merged in 2025-06, with the labels that each got.

#3663 Create index image out of bundle images from Konflux
  hack/generate/dockerfile.sh
  olm-catalog/serverless-operator-index/Dockerfile
Labels: approved, lgtm, ok-to-test

#3713 :bug: Changes for ODC 4.19+
  test/ui-e2e-tests.sh
  test/ui/cypress/code/knative/serving/showcase.js
  test/ui/cypress/code/openshift/openshiftConsole.js
  test/ui/cypress/e2e/serving/multiple-revisions.cy.js
Labels: approved, lgtm

#3720 [release-1.36] Update Konflux configurations
  .tekton/serverless-index-136-fbc-419-pull-request.yaml
  .tekton/serverless-index-136-fbc-419-push.yaml
Labels: approved, lgtm

#3730 fix multiple entry at url and revision and dockerfile url of net-istio-controller
  .konflux-release/override-snapshot.yaml
Labels: approved, lgtm

#3733 new-override-snapshot-after-net-istio-fix
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot-fbc-419.yaml
  .konflux-release/override-snapshot.yaml
Labels: approved
