Repository openshift-knative/serverless-operator, pull requests merged in 2025-01, with the labels that each got.

#3285 [release-1.35] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#3288 [release-1.35] Update renovate.json to exclude unwanted updates
  renovate.json
Labels: approved, lgtm

#3277 Update knative.dev/eventing component
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/jobsink/jobsink.go
  vendor/modules.txt
Labels: approved, lgtm

#3279 [release-1.35] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
  .tekton/serverless-bundle-135-pull-request.yaml
  .tekton/serverless-bundle-135-push.yaml
  .tekton/serverless-ingress-135-pull-request.yaml
  .tekton/serverless-ingress-135-push.yaml
  .tekton/serverless-kn-operator-135-pull-request.yaml
  .tekton/serverless-kn-operator-135-push.yaml
  .tekton/serverless-metadata-webhook-135-pull-request.yaml
  .tekton/serverless-metadata-webhook-135-push.yaml
  .tekton/serverless-must-gather-135-pull-request.yaml
  .tekton/serverless-must-gather-135-push.yaml
  .tekton/serverless-openshift-kn-operator-135-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-135-push.yaml
Labels: needs-ok-to-test

#3335 [release-1.35] Bump image references
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#3333 [release-1.35] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/fbc-builder.yaml
Labels: needs-ok-to-test

#3278 [main] Add Konflux configurations
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: needs-ok-to-test

#3338 Add revision alignment check for images in CSV
  Makefile
  hack/lib/images.bash
  hack/verify-csv-revisions.sh
Labels: approved, lgtm

#3344 Make the name of the override-snapshot predictable
  hack/generate/override-snapshot.sh
Labels: approved, lgtm

#3345 Add target to apply override-snapshot
  Makefile
Labels: approved, lgtm

#3352 Bump skopeo to 1.17.0
  Makefile
  openshift/ci-operator/build-image/Dockerfile
  templates/build-image.Dockerfile
Labels: approved, lgtm

#3355 Exclude override-snapshot generateName from diff check
  hack/verify-diff.sh
Labels: approved, lgtm

#3354 Add branch label to generated override snapshots
  .konflux-release/override-snapshot-fbc-414.yaml
  .konflux-release/override-snapshot-fbc-415.yaml
  .konflux-release/override-snapshot-fbc-416.yaml
  .konflux-release/override-snapshot-fbc-417.yaml
  .konflux-release/override-snapshot-fbc-418.yaml
  .konflux-release/override-snapshot.yaml
  hack/generate/override-snapshot.sh
Labels: approved, lgtm

#3351 Inject Istio sidecar for JobSink
  hack/lib/serverless.bash
Labels: approved, lgtm

#3362 Update Eventing to fix TestJobSinkSuccess
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/knative.dev/eventing/test/rekt/features/jobsink/jobsink.go
  vendor/knative.dev/eventing/test/rekt/resources/jobsink/jobsink.go
  vendor/modules.txt
Labels: approved, lgtm

#3364 Bump Eventing to v1.16
  Makefile
  knative-operator/deploy/resources/knativekafka/broker/eventing-kafka-broker.yaml
  knative-operator/deploy/resources/knativekafka/channel/eventing-kafka-channel.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-controller.yaml
  knative-operator/deploy/resources/knativekafka/controller/eventing-kafka-post-install.yaml
  knative-operator/deploy/resources/knativekafka/sink/eventing-kafka-sink.yaml
  knative-operator/deploy/resources/knativekafka/source/eventing-kafka-source.yaml
  olm-catalog/serverless-operator-index/Dockerfile
  olm-catalog/serverless-operator/manifests/serverless-operator.clusterserviceversion.yaml
  olm-catalog/serverless-operator/project.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-backstage-plugins-eventmesh-backend.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-eventing-crds.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/1-eventing-istio-controller.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/2-eventing-core.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/3-in-memory-channel.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/4-mt-channel-broker.yaml
  openshift-knative-operator/cmd/openshift-knative-operator/kodata/knative-eventing/latest/5-eventing-post-install.yaml
  openshift/ci-operator/source-image/Dockerfile
  test/images-rekt.yaml
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
Labels: approved, lgtm

#3360 Fix SO version in override snapshot generation
  hack/generate/override-snapshot.sh
Labels: approved, lgtm

#3357 [main] Update Konflux configurations
  .tekton/serverless-bundle-136-pull-request.yaml
  .tekton/serverless-bundle-136-push.yaml
  .tekton/serverless-index-136-fbc-414-pull-request.yaml
  .tekton/serverless-index-136-fbc-414-push.yaml
  .tekton/serverless-index-136-fbc-415-pull-request.yaml
  .tekton/serverless-index-136-fbc-415-push.yaml
  .tekton/serverless-index-136-fbc-416-pull-request.yaml
  .tekton/serverless-index-136-fbc-416-push.yaml
  .tekton/serverless-index-136-fbc-417-pull-request.yaml
  .tekton/serverless-index-136-fbc-417-push.yaml
  .tekton/serverless-index-136-fbc-418-pull-request.yaml
  .tekton/serverless-index-136-fbc-418-push.yaml
  .tekton/serverless-ingress-136-pull-request.yaml
  .tekton/serverless-ingress-136-push.yaml
  .tekton/serverless-kn-operator-136-pull-request.yaml
  .tekton/serverless-kn-operator-136-push.yaml
  .tekton/serverless-metadata-webhook-136-pull-request.yaml
  .tekton/serverless-metadata-webhook-136-push.yaml
  .tekton/serverless-must-gather-136-pull-request.yaml
  .tekton/serverless-must-gather-136-push.yaml
  .tekton/serverless-openshift-kn-operator-136-pull-request.yaml
  .tekton/serverless-openshift-kn-operator-136-push.yaml
Labels: approved, needs-ok-to-test

#3342 Add workflow for CSV revision alignment check
  .github/workflows/csv-revision-check.yaml
Labels: approved
